### ISSUE TITLE
Support for Kibana 4 dashboards

### ISSUE THREAD

**Issue by richardkerr** [stagemonitor/stagemonitor#100]
The dashboards are currently developed for Kibana 3 and are incompatible with Kibana 4.  

I spent quite a bit of time trying to figure out why the dashboards were not showing for me before stumbling across the incompatibilities of Kibana 3 and 4.  

I understand the size of this task is probably quite large, but for the mean time a documentation update of the supported versions of ES / Kibana / etc could be useful to others in my position.

**Comment by felixbarny** [comment]
I'm already working on Kibana 4 and Grafana 2 support. It's in the influxdb branch. The documentation is updated. Thx!

**Comment by felixbarny** [comment]
closed in #111
