### ISSUE TITLE
Instrumentation Inside of EJB Classes

### ISSUE THREAD

**Issue by alexeyromanchuk** [stagemonitor/stagemonitor#103]
Hi !

I have a Spring MVC application which does some EJB calls. Those EJB classes are located in the same war file as the application. But stagemonitor instrumentation performs processing MVC classes and ejb remote interfaces only and doesn't the classes which are inside of the EJBs (inside of each EJB are lots of other spring-based business logic). So that I can't see more detailed callStacks (it's restricted by the ejb remote interfaces only).

In the code I found that the problem might be mostly connected with using different classloaders for web and ejb classes but maybe I've just missed some important steps for this scenario?

I'm using Glassfish 4.1 Application Server to deploy the war file. In the case when I try to run the App with Glassfish in the embedded mode (with unit tests) all is ok - I see the full callStack.

Thank you in advance!

**Comment by felixbarny** [comment]
What do you mean by the classes inside the EJBs? Are they in a separate jar or war? What's currently problematic is when you have an ear which contains a war and a (ejb) jar. In that case you won't be able to se a complete call tree across the classes in the war and the ejb jar due to - you said it - different classloaders.

**Comment by alexeyromanchuk** [comment]
The EJB classes are in the same war, not in a jar (in this application we don't use ear files). But now I see some errors like 'failed to transform' with the names of the EJB classes in my application log. Trying to investigate this 'failed' more.

**Comment by alexeyromanchuk** [comment]
Finally, I've faced with another trouble. When the stagemonitor javaagent is attempting to start on a Glassfish Application Server, it puts some non-string property values to system properties and my Embedded JMS Server (OpenMQ actually) is unable to cope with these values and fails (its configuration expects string values). But in the case of using non-embedded JMS all is ok.
Not sure it's a critical but still.

**Comment by felixbarny** [comment]
That's basically what is described in #99

**Comment by felixbarny** [comment]
This should be fixed in the current version. If not, feel free to reopen.
