### ISSUE TITLE
need to run docker container with --privileged

### ISSUE THREAD

**Issue by maklemenz** [stagemonitor/stagemonitor#104]
I used the provided script to set up a local test instance:
curl -s https://raw.githubusercontent.com/stagemonitor/stagemonitor-docker/master/start | sh

The container died instantly.

$ sudo docker logs stagemonitor
/usr/lib/python2.7/dist-packages/supervisor/options.py:295: UserWarning: Supervisord is running as root and it is searching for its configuration file in default locations (including its current working directory); you probably want to specify a "-c" argument specifying an absolute path to a configuration file for improved security.
  'Supervisord is running as root and it is searching '
Traceback (most recent call last):
  File "/usr/bin/supervisord", line 9, in <module>
    load_entry_point('supervisor==3.0b2', 'console_scripts', 'supervisord')()
  File "/usr/lib/python2.7/dist-packages/supervisor/supervisord.py", line 360, in main
    go(options)
  File "/usr/lib/python2.7/dist-packages/supervisor/supervisord.py", line 370, in go
    d.main()
  File "/usr/lib/python2.7/dist-packages/supervisor/supervisord.py", line 77, in main
    info_messages)
  File "/usr/lib/python2.7/dist-packages/supervisor/options.py", line 1312, in make_logger
    stdout = self.nodaemon,
  File "/usr/lib/python2.7/dist-packages/supervisor/loggers.py", line 344, in getLogger
    handlers.append(RotatingFileHandler(filename,'a',maxbytes,backups))
  File "/usr/lib/python2.7/dist-packages/supervisor/loggers.py", line 172, in __init__
    FileHandler.__init__(self, filename, mode)
  File "/usr/lib/python2.7/dist-packages/supervisor/loggers.py", line 98, in __init__
    self.stream = open(filename, mode)
IOError: [Errno 13] Permission denied: '/var/log/supervisor/supervisord.log'

Worked just fine after adding --privileged.

I'm using fedora 22 with docker version 1.8.2-fc22:

Client:
 Version:      1.8.2-fc22
 API version:  1.20
 Package Version: docker-1.8.2-1.gitf1db8f2.fc22.x86_64
 Go version:   go1.4.2
 Git commit:   f1db8f2/1.8.2
 Built:        
 OS/Arch:      linux/amd64

Server:
 Version:      1.8.2-fc22
 API version:  1.20
 Package Version: 
 Go version:   go1.4.2
 Git commit:   f1db8f2/1.8.2
 Built:        
 OS/Arch:      linux/amd64

**Comment by felixbarny** [comment]
So do you propose that I should add the --privileged switch to the start script? When is it needed? Only on fedora?

**Comment by maklemenz** [comment]
I don't want to propose to add --privileged as default.

It turned out that this issue is a known issue on all systems with selinux:
https://github.com/docker/docker/pull/5910

In a short test I added the z-flags to the volume mounts, as suggested in the docker ticket:

    docker run -d \
	-v /var/docker/stagemonitor/elastic:/var/lib/elasticsearch:z \
	-v /var/docker/stagemonitor/graphite:/opt/graphite/storage/whisper:z \
	-v /var/docker/stagemonitor/supervisor:/var/log/supervisor:z \
	-p 18888:80 \
        -p 18181:81 \
        -p 12003:2003/tcp \
        --name stagemonitorZ stagemonitor/stagemonitor-docker

worked without any issue.

I don't have a system without selinux around, so I can't test for issues on them caused by this flag. If that wouldn't cause issues I would suggest to add the z-flag rather than --privileged.

**Comment by felixbarny** [comment]
Closing as stagemonitor-docker is deprecated. Please refer to https://github.com/stagemonitor/stagemonitor/wiki/Step-2%3A-Request-Analysis-Dashboard#set-up-with-docker-compose how to use stagemonitor with docker and docker-compose.
