### ISSUE TITLE
stagemonitor-elasticsearch

### ISSUE THREAD

**Issue by yanwork** [stagemonitor/stagemonitor#106]
Consider implementing monitoring of application's requests to elasticsearch (not one used by stagemonitor itself, but applied) -  query [and maybe other API requests]

**Comment by felixbarny** [comment]
Elasticsearch queries are already visible in the call tree

**Comment by yanwork** [comment]
Great!  Thanks for implementing.

Maybe you have another suggestions about  -elasticsearch plugin? 
If not - we can close the issue now.
