### ISSUE TITLE
Stagemonitor.init() calls reset() which calls SharedMetricRegistries.clear()

### ISSUE THREAD

**Issue by marcust** [stagemonitor/stagemonitor#107]
We just ran into that issue while trying to activate Spring Boot metrics and run this through the same metrics registry as Stagemonitor.

As the Spring init actually ran before Stagemonitor this deleted the registry we tried to share between Spring and Stagemonitor. 

The comment on reset() says 
```      
    /**
	 * Should only be used by the internal unit tests
	 */
```	

I agree.

**Comment by felixbarny** [comment]
Have you set up stagemonitor like this: https://github.com/stagemonitor/stagemonitor/wiki/Step-1:-Prerequisites#spring-boot? Especially the init in the main method is important.

**Comment by felixbarny** [comment]
What do you mean with activating Spring Boot metrics? How do you do that?

**Comment by marcust** [comment]
This is Spring Boot metrics:
http://docs.spring.io/spring-boot/docs/current/reference/html/production-ready-metrics.html#production-ready-code-hale-metrics
So basically bind the Registry called "stagemonitor" to the @Bean MetricRegistry.

I think we might have missed the Stagemonitor.init() call in the beginning of the main Method, but I'm still sure that Stagemonitor should not clear the SharedMetricsRegistry.

**Comment by felixbarny** [comment]
Probably this line in reset is problematic: `SharedMetricRegistries.clear();` as it does not only clear stagemonitor created metrics.

**Comment by marcust** [comment]
Yes, that is the issue

**Comment by felixbarny** [comment]
Ok, I agree
