### ISSUE TITLE
Demo site is down

### ISSUE THREAD

**Issue by rajeshkp** [stagemonitor/stagemonitor#115]
http://stagemonitor-demo.isys-software.de/

Service Unavailable

The server is temporarily unable to service your request due to maintenance downtime or capacity problems. Please try again later.

**Comment by ponschab** [comment]
Thanks for the hint. The service was down by mistake.

**Comment by tetreum** [comment]
Demo is down again, shows a.. pet website?

**Comment by felixbarny** [comment]
This is the demo of the in browser widget. Click on the speaker icon on the bottom right corner to see the magic :)

**Comment by tetreum** [comment]
Uh fail. Users like me require a GIANT text + arrow ["DEMO =>"]
Ty for fast reply!
