### ISSUE TITLE
Classloader/memory leaks on redeploy due to orphaned threads (Wildfly 9.0.x)

### ISSUE THREAD

**Issue by ryanrupp** [stagemonitor/stagemonitor#119]
I'm trying to move to 0.19.2 to get the thread leak fix for the request-trace remover but noticed there's another issue there where when I undeploy or redeploy my application the classloader reference isn't able to be collected.  Looking into this it looks to be because the hot/cold migration timer tasks are leaking threads. This here - https://github.com/stagemonitor/stagemonitor/blob/1f18e0f3d3c8ec72733e5c3ab363d7751711a038/stagemonitor-core/src/main/java/org/stagemonitor/core/elasticsearch/ElasticsearchClient.java#L289

Ideally this could just share the asyncRestPool (and shutdown then with it) by changing it to a scheduled executor because I noticed this ends up spawning two long lived threads (one for both metrics and requests indices) which could be avoided. Not sure how long those index operations take e.g. if they shared a thread pool is it being single threaded sufficient to support both those operations + reporting to elasticsearch, could move the thread pool to a cached thread pool with a core size of 1 and max of 5 or something like that.

I've just been using Eclipse Memory Analyzer to narrow this down but Tomcat has good support for catching this and trying to fix it / logging something - http://wiki.apache.org/tomcat/MemoryLeakProtection#cclThreadSpawnedByWebApp

Another issue I ran into that's specific to Wildfly is that Wildfly by default lazy loads Filters so if I redeployed back to back for some reason without using the application (sometimes do this in development if I catch something wrong right away), it ends up not shutting down Stagemonitor because Stagemonitor.shutDown() is called as part of the HttpRequestMonitorFilter's destroy which doesn't get called if it never got initialized. This is unique to Wildfly though and I'll probably just safeguard for this by having my app due a Stagemonitor.shutDown() as well or there is an option now in Wildfly (but you have to configure it on the container) to due eager initialization by default - https://issues.jboss.org/browse/WFLY-3028 - figured I'd mention it here incase anyone runs into this.

**Comment by felixbarny** [comment]
I cant reuse the assncRestPool because I need a `Timer` to execute the tasks at a certain time. But I should store the Timer in an instance variable and close it on shutdown.

**Comment by ryanrupp** [comment]
I was thinking you could change the asyncRestPool to a ScheduledExecutorService (sub interface of ExecutorService so still have submit/execute available but with scheduling) - the API is slightly different than Timer in that it doesn't take a Date for the first execution but rather a delay so you could do:

```
scheduledExecutor.scheduleAtFixedRate(
    taskAsRunnable, DateUtils.getNextDateAtHour(0).getTime() - System.currentTimeMillis(),
    DateUtils.getDayInMillis(), TimeUnit.MILLISECONDS);
```

**Comment by ryanrupp** [comment]
I missed that the queue is bounded for the thread pool so ScheduledThreadPoolExecutor wouldn't work as it uses an unbounded queue I believe. So the Timer as an instance variable would be good as you mentioned so it can get closed.
