### ISSUE TITLE
Shutdown hook causes classloader/memory leak

### ISSUE THREAD

**Issue by ryanrupp** [stagemonitor/stagemonitor#126]
Hey, I'm still trying to work through re-deployment leaks with Stagemonitor in conjunction with Wildfly (but applicable to other web servers although Tomcat safeguards some of this stuff). Latest thing I noticed is registering a shutdown hook with the runtime is causing a leak to occur because of the use of a thread (although it's not started) it holds a reference then to the context class loader which chains its way down the application preventing garbage collection from happening. This code here - https://github.com/stagemonitor/stagemonitor/blob/36012286f4528bcadf56c82dd3b210a0f105ee21/stagemonitor-core/src/main/java/org/stagemonitor/core/Stagemonitor.java#L104 - ideally if it's detected a web server environment is used the runtime hook wouldn't be registered (or at least it would be deregistered) and the shutdown hook is just run when the servlet/filter is destroyed (this is already there).

**Comment by ryanrupp** [comment]
Also, I'm not sure if the P6SpyDriver causes a leak because it's registered with the DriverManager (system/global level) but never unregistered, was going to get the shutdown hook fixed then see where we're at.

**Comment by felixbarny** [comment]
thx for catching this!
