### ISSUE TITLE
AspectJ LTW-Woven classes loose their aspects if stagemonitor is used

### ISSUE THREAD

**Issue by bjung82** [stagemonitor/stagemonitor#130]
Hi,

we use AspectJ-Loadtime weaving for e.g. persistence. Classes that are already woven this
way loose their aspects, because they are reloaded later by stage-monitor (without their aspects).

The problem seems to be located in org.stagemonitor.core.instrument.MainStagemonitorClassFileTransformer.getCtClass(ClassLoader, byte[], String)

The second argument (byte[] classfileBuffer) is not used by this method at all. This causes the loss of the aspects.

Kind regards
Benjamin

**Comment by felixbarny** [comment]
I have just released 0.22.0, which contains the fix.

**Comment by bjung82** [comment]
Thank you very much, I'll give it a try next week :-)

**Comment by bjung82** [comment]
Now it looks really nice, your bugfix works. Thank you very much :-)
