### ISSUE TITLE
stagemonitor fails to launch in a spring boot app launched as a service

### ISSUE THREAD

**Issue by coding-tyro** [stagemonitor/stagemonitor#134]
Hi,

stagemonitor runs well when I execute my java application as a jar, but fails when I link my jar as a service and then execute it.(It's a Spring Boot Java Application)

http://docs.spring.io/spring-boot/docs/current/reference/html/deployment-install.html

Exception Includes:-

INFO: Unavailable or unrecognised attach API : java.lang.ClassNotFoundException: com.sun.tools.attach.VirtualMachine
 [main] INFO  o.s.c.i.MainStagemonitorClassFileTransformer - Registering ExceptionMeteredInstrumenter
 [main] INFO  o.s.c.i.MainStagemonitorClassFileTransformer - Registering MeteredInstrumenter
 [main] INFO  o.s.c.i.MainStagemonitorClassFileTransformer - Registering TimedInstrumenter
 [main] INFO  o.s.c.i.MainStagemonitorClassFileTransformer - Registering GaugeInstrumenter
 [main] WARN  o.s.c.i.MainStagemonitorClassFileTransformer - Failed to perform runtime attachment of the stagemonitor agent. You can load the agent with the command line argument -javaagent:/path/to/stagemonitor-javaagent-<version>.jar
java.lang.NullPointerException: null
        at org.stagemonitor.core.instrument.MainStagemonitorClassFileTransformer.performRuntimeAttachment(MainStagemonitorClassFileTransformer.java:90) ~[stagemonitor-core-0.20.0.jar!/:0.20.0]
        at org.stagemonitor.core.Stagemonitor.reset(Stagemonitor.java:227) [stagemonitor-core-0.20.0.jar!/:0.20.0]
        at org.stagemonitor.core.Stagemonitor.<clinit>(Stagemonitor.java:38) [stagemonitor-core-0.20.0.jar!/:0.20.0]
        at *PACKAGE_NAME*(Test.java:22) [spring-boot-demo.jar!/:0.0.1-SNAPSHOT]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_51]
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_51]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_51]
        at java.lang.reflect.Method.invoke(Method.java:497) ~[na:1.8.0_51]
        at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:54) [spring-boot-demo.jar!/:0.0.1-SNAPSHOT]
        at java.lang.Thread.run(Thread.java:745) [na:1.8.0_51]
[pool-1-thread-1] WARN  org.stagemonitor.core.Stagemonitor - Measurement Session is not initialized: [application=spring-boot-demo] [instance=Test] **[host=null]**

This seems to occur as host gets set to null, when starting as service. While executing as jar, this sets automatically to host name of machine. I didn't find any way to provide this as parameter in stagemonitor.properties file. Please Help.

**Comment by felixbarny** [comment]
The possibility to provide a custom host name was just recently added in #133. Also, stagemonitor tries to read the environment variables `COMPUTERNAME` and `HOSTNAME`. You could check why they are not set when launching the application as a service.

**Comment by coding-tyro** [comment]
Well, this got resolved. Thanks.

But still, I am not able to ship JDBC metrics to the elasticsearch instance we have. (Therefore JDBC, dashboard is not getting populated). How to do this for a Spring Boot Java App?

**Comment by felixbarny** [comment]
Which database driver and connection pool are you using? What are your settings? Could you provide a minimal example application that reproduces the problem? That would enable me to quickly resolve this issue.

**Comment by coding-tyro** [comment]
Hi Felix,

I am trying to implement this on a dummy spring boot app.

Major code snippets that might help you are provided below:-

CLASS:- TEST.JAVA

//All_Required_Imports

@RestController
@EnableAutoConfiguration
@SpringBootApplication

public class Test {

	@RequestMapping("/")
	String home() {
		return "HELLO WORLD";

	}

	public static void main(String[] args) throws Exception {
	
		int i;

		PGPoolingDataSource source = new PGPoolingDataSource();
		source.setDataSourceName("ds_name");
		source.setServerName("SERVER ADRESS");
		source.setDatabaseName("DB NAME");
		source.setUser("USERNAME");
		source.setPassword("PASSWORD");
		source.setMaxConnections(4);
		Thread.sleep(100);

		Stagemonitor.init();
		SpringApplication.run(Test.class, args);
		
			for (i = 0; i < 10; i++) {
			Connection con = null;
			con = source.getConnection();
			System.out.println("Creating statement...");
			Statement stmt;
			stmt = con.createStatement();
			String sql;
			sql = "SQL STRING";
			
			ResultSet rs = stmt.executeQuery(sql);

			 while(rs.next()){
		         //Retrieve by column name
		         String any_field = rs.getString("ANY_FIELD");
		        
		         //Display values
		         System.out.print("FIELD VALUE: " + any_field); 
		      }
			con.close();
		}
	}
}
			
STAGEMONITOR PROPERTIES FILE:-

stagemonitor.reporting.elasticsearch.deleteMetricsAfterDays=7
stagemonitor.applicationName=spring-boot-demo
stagemonitor.instanceName=Test
stagemonitor.hostName=spring-boot-demo-test
stagemonitor.elasticsearch.url=ELASTICSEARCH_URL
stagemonitor.instrument.include=TEST CLASS PACKAGE
stagemonitor.instrument.jdbc.dataSource.implementations=org.postgresql.ds.PGPoolingDataSource

pom.xml:-(Only Stagemonitor Dependencies)

		<dependency>
			<groupId>org.stagemonitor</groupId>
			<artifactId>stagemonitor-core</artifactId>
			<version>0.21.0-SNAPSHOT</version>
		</dependency>

		<dependency>
			<groupId>org.stagemonitor</groupId>
			<artifactId>stagemonitor-jdbc</artifactId>
			<version>0.21.0-SNAPSHOT</version>
		</dependency>
		<dependency>
			<groupId>org.stagemonitor</groupId>
			<artifactId>stagemonitor-jvm</artifactId>
			<version>0.21.0-SNAPSHOT</version>
		</dependency>

		<dependency>
			<groupId>org.stagemonitor</groupId>
			<artifactId>stagemonitor-os</artifactId>
			<version>0.21.0-SNAPSHOT</version>
		</dependency>
		
**This ia all I have done. Is there something I am missing upon which needs to additionally done than what is mention above? Any help would be appreciated.**

Thanks
