### ISSUE TITLE
Docs unclear how to install it

### ISSUE THREAD

**Issue by waleedsaud** [stagemonitor/stagemonitor#135]
Docs unclear how to install it.
is it an agent that sends to elasticsearch, or an agent that send metric to a central apm server?
how does it monitor application?
Is it only JAVA apps?

**Comment by felixbarny** [comment]
Hi, thank you very much for you question. I reworked the entry site of the wiki to address your questions. Please let me know if there is still something unclear.
https://github.com/stagemonitor/stagemonitor/wiki

<img width="804" alt="call-tree" src="https://cloud.githubusercontent.com/assets/2163464/13771352/68e0b628-ea8d-11e5-86b1-3a2239d64821.png">

**Comment by waleedsaud** [comment]
thank you.
