### ISSUE TITLE
Deployment  Guide

### ISSUE THREAD

**Issue by rohitrsh** [stagemonitor/stagemonitor#137]
Hi,

Could you please share link of complete stagemonitor deployment guide?

-Rohit

**Comment by felixbarny** [comment]
This is the installation guide: https://github.com/stagemonitor/stagemonitor/wiki/Installation

If you think there is something missing or unclear, please give me feedback

**Comment by rohitrsh** [comment]
Hi,

None of the link having any data, also i am looking for to install on VM not on docker

Step 1: Prerequisites
Step 2: Log Only Monitoring/In Browser Widget
Step 3: Requests and Call Stacks Dashboard
Step 4: Metrics Dashboard
Next Steps

**Comment by felixbarny** [comment]
Thx for catching this! The links where indeed stale. Fixed this
