### ISSUE TITLE
Stagemonitor: problem with MainStagemonitorClassFileTransformer

### ISSUE THREAD

**Issue by gauravrmazra** [stagemonitor/stagemonitor#140]
MainStagemonitorClassFileTransformer sets IGNORED_CLASSLOADERS_KEY with some object. 

Now I am using Teiid and narayana jta for transaction management. In narayana, it is failing because in AbstractPropertiesFactory#applySystemProperties System.getProperty[this returns null if value is not instance of String class] return null for the above mentioned key of MainStagemonitorClassFileTransformer and which causes NPE.

**Comment by felixbarny** [comment]
Duplicate of #99
My next prio is an overhaul of the bytecode manipulation

**Comment by gauravrmazra** [comment]
When can we expect this issued will be fixed?

**Comment by felixbarny** [comment]
At the moment I can't give a ETA other than that this is high prio. I first have to analyze the problem more deeply.
