### ISSUE TITLE
Widget - JQuery treetable performance issue with Chrome

### ISSUE THREAD

**Issue by ryanrupp** [stagemonitor/stagemonitor#141]
v0.20.0 of Stagemonitor - I noticed when using Chrome (version 49.0.2623.87 on OSX, although verified against Windows + Chrome as well), when working on some pages where a few requests are made where they have a larger request traces (basically Hibernate is very verbose about the SQL it generates and we're traversing the entity graph fairly deeply with batch selects so there's a good amount of large SQL statements) - the browser hangs for a while (10-15 seconds) with the CPU spinning. I captured a Chrome CPU profile of this (attached) and it looks like it has something to do with rendering the request trace with JQuery treetables. This is from a page load where the Stagemonitor widget is available however it is not opened. Interesting part is that this issue does not occur for me on Firefox or Safari. Also tried this with incognito mode (no extensions enabled to rule that out) and issue persisted. Not sure if this is a defect with Chrome or something with treetable or with the way treetable is being used but figured I'd log it here for now. I also tested against an older version of Stagemonitor (0.18.0) because I hadn't really noticed this as much before, the issue exists in that version too but seemed to be not as pronounced.

[cpuProfileOfLoadingFormWithStagemonitor.cpuprofile.zip](https://github.com/stagemonitor/stagemonitor/files/200281/cpuProfileOfLoadingFormWithStagemonitor.cpuprofile.zip)

**Comment by felixbarny** [comment]
Are you sure that you did not open the widget? Actually, the call tree only gets rendered when you open the widget. The rendering then can take a couple of seconds when the call tree is very large. In order to make the call tree smaller, you could tweak the [`stagemonitor.profiler.minExecutionTimePercent`](https://github.com/stagemonitor/stagemonitor/wiki/Configuration-Options#min-execution-time-) setting.

**Comment by felixbarny** [comment]
Could it be that the slow call tree stems from ajax request traces?

**Comment by ryanrupp** [comment]
This is with the widget closed. I debugged the client code and found the renderTree call is happening from here - https://github.com/stagemonitor/stagemonitor/blob/763088ea7ffdd57b5a724dd7a8733b4b51565fe3/stagemonitor-web/src/main/resources/stagemonitor/static/tabs/ajax-requests.js#L85 - with the widget closed it goes down this code path which ends up in this rendering callback - https://github.com/stagemonitor/stagemonitor/blob/763088ea7ffdd57b5a724dd7a8733b4b51565fe3/stagemonitor-web/src/main/resources/stagemonitor/static/tabs/call-tree-tab.js#L26

I worked around this by making the scroll property default to "false" - https://github.com/stagemonitor/stagemonitor/blob/763088ea7ffdd57b5a724dd7a8733b4b51565fe3/stagemonitor-web/src/main/resources/stagemonitor/static/tabs/ajax-requests.js#L83 - by setting the local storage property e.g. localStorage.setItem("stagemonitor-widget-ajax-autoscroll”, “false”)

With that change the pages in question load quickly again. Then when I open the widget it's just not selected on the last request but when I navigate manually between the requests it renders fine (in terms of CPU time, renders without it being noticeable as a user in terms of time). I'm not sure this answers why even if it loads without the widget being open why it's slow on Chrome but not Firefox/Safari.

As a side note should the JQuery $.get of the HTML tab automatically get cached? Noticed when I load a form this callback to load the HTML template gets called a fair amount resulting in the HTTP request to get the HTML page. Not sure if I should be adding HTTP caching headers to make it cache but I thought maybe JQuery has its own form of caching e.g. found a few SO posts about how to disable JQuery caching - http://stackoverflow.com/questions/367786/prevent-browser-caching-of-jquery-ajax-call-result - just wondering because AngularJS does this with how it loads partial template HTML files even though the HTTP cache headers aren't present (caches the page load in its own cache rather than browser cache).

**Comment by ryanrupp** [comment]
Example of loading a form, because the form has multiple drop down (combo boxes) that need to be populated from the server there's multiple AJAX requests going on that then result in the long poll "request-traces" request being fulfilled then the callback loads the request-tab/call-tree html pages.
<img width="861" alt="screen shot 2016-04-02 at 2 03 54 pm" src="https://cloud.githubusercontent.com/assets/3022260/14228493/0a76b580-f8dc-11e5-97b3-393c97f3a7e5.png">

**Comment by felixbarny** [comment]
I see.  So the fix would be to lazily render the call tree, even if `stagemonitor-widget-ajax-autoscroll=true`. I agree the tenplates should somehow be cached.
