### ISSUE TITLE
Customise ES index properties

### ISSUE THREAD

**Issue by rafelbev** [stagemonitor/stagemonitor#142]
Is it possible to customise the properties of the index created in ElasticSearch? We would be interested to always use best compression. We are currently doing the following:

curl -XPOST 'localhost:9200/stagemonitor-requests-2016.04.03/_close'
curl -XPUT 'localhost:9200/stagemonitor-requests-2016.04.03/_settings' -d '{"index.codec": "best_compression" }'
curl -XPOST 'localhost:9200/stagemonitor-requests-2016.04.03/_open'
curl -XPOST 'localhost:9200/stagemonitor-requests-2016.04.03/_optimize?max_num_segments=1'

This can only be done for a non-active index as it needs to be closed to manage to update the index.codec. Is there a way which allows us to create the new daily index using that codec write from the start?

I see that we are only setting the refresh interval here:
[a link](https://github.com/stagemonitor/stagemonitor/blob/influxdb/stagemonitor-requestmonitor/src/main/resources/stagemonitor-elasticsearch-request-index-template.json)

**Comment by felixbarny** [comment]
Are you seeing improvements in terms of disk usage? Maybe it would make sense to just make this the default. Or do you want to customize more settings?

**Comment by rafelbev** [comment]
I'm seeing half disk usage day on day over the last 4 days. In the long term I would still make it configurable. Different applications, different needs.

**Comment by felixbarny** [comment]
Another option for you would be to modify the `elasticsearch.yml` so that all indices of the node use `best_compression`.
