### ISSUE TITLE
Ease of hostName configuration in amazon images

### ISSUE THREAD

**Issue by yacota** [stagemonitor/stagemonitor#146]
As mentioned in the documentation hostName is resolved as follows

The host name. If this property is not set, the host name will default to resolving the host name for localhost, if this fails it will be loaded from the environment, either from COMPUTERNAME or HOSTNAME.

But in an Amazon environment where the same image is deployed into multiple instances this means that the same hostName is resolved.
We can set an environment variable during the image boot process but unfortunately it won't be used according to the documentation.

Any chance to resolve HOSTNAME, COMPUTERNAME or "a new variable"  prior to anything else?

**Comment by felixbarny** [comment]
Did you try the environment variable STAGEMONITOR_HOSTNAME?

**Comment by yacota** [comment]
I haven't tried STAGEMONITOR_HOSTNAME and regarding property files I prefer to avoid maintaining N.
Thanks

**Comment by felixbarny** [comment]
The link is about configuring stagemonitor via environment variables. I'm not proposing you should use property files. All configuration options are also configurable via environment variables:

> You can also use environment variables to configure stagemonitor. Due to different naming conventions, the config keys have to be upper-cased and all dots have to be replaced with underscores. Example: to specify the config key stagemonitor.active as a environment variable, it has to be named STAGEMONITOR_ACTIVE.

**Comment by yacota** [comment]
That is pure gold
👍
