### ISSUE TITLE
Custom metrics only work when Graphite is enabled?

### ISSUE THREAD

**Issue by yacota** [stagemonitor/stagemonitor#158]
Custom metrics dashboard as explained here https://github.com/stagemonitor/stagemonitor/wiki/Track-your-own-metrics should contain all metrics created by the annotations BUT in the CorePlugin code I only see the dashboard created when graphite is enabled

```
...   
ElasticsearchClient elasticsearchClient = getElasticsearchClient();
if (isReportToGraphite()) {
elasticsearchClient.sendGrafana1DashboardAsync("Grafana1GraphiteCustomMetrics.json");
}
...
```

**Comment by felixbarny** [comment]
Good catch. The custom metrics dahsboard has not been converted to elasticsearch yet.

**Comment by yacota** [comment]
Awesome as usual @felixbarny
