### ISSUE TITLE
Setup Stagemonitor with Spring Boot Project for REST-APIs

### ISSUE THREAD

**Issue by Grosskopferter** [stagemonitor/stagemonitor#160]
Hi,
thanks for this awesome project!
I set up stagemonitor for a Spring Boot Project that only provides REST-APIs and no web pages according to the documentation here: https://github.com/stagemonitor/stagemonitor/wiki/Integrate-stagemonitor-into-non-servlet-based-applications

To add request monitoring I added the @MonitorRequest annotation to all methods with a requestMapping in my Controllers:
```
@MonitorRequests
@RequestMapping(value = "...", method = RequestMethod.GET)
public Object get...(...)
```

This works good, I only wonder whether there is any better way that automatically picks all endpoints in the project for monitoring (and some fields as status code are not automatically aggregated like this)

Thanks!

**Comment by ryanrupp** [comment]
The way you're using Spring Boot should still be a servlet environment it's just using an embedded Tomcat. I haven't tried specifically with Spring Boot but did you try including stagemonitor-web in your dependencies?

**Comment by felixbarny** [comment]
stagemonitor-web works with Spring Boot. See also https://github.com/stagemonitor/stagemonitor-integration-tests/tree/master/spring-boot-sample-jpa for an example and https://github.com/stagemonitor/stagemonitor/wiki/Step-1%3A-In-Browser-Widget#spring-boot for the Spring Boot specific installation step.
