### ISSUE TITLE
Error in 'Gauges' graphic in 'Custom Metrics' dashBoard

### ISSUE THREAD

**Issue by xgimenezs** [stagemonitor/stagemonitor#161]
I think there is an error in 'ElasticsearchCustomMetricsDashboard.json'. Gauges graphic don't group by term previously to make the histograms.

**Comment by felixbarny** [comment]
Thx for the report, but I don't quite get what's the error. Could you post a screenshot and explain what the expected behavior is?

**Comment by xgimenezs** [comment]
PR just created :)

**Comment by felixbarny** [comment]
Ok, I think I get it now. Basically `{{term name}}` was missing, right? Thx for the PR :)

**Comment by xgimenezs** [comment]
You are welcome.
I think GroupBy was missing too.
