### ISSUE TITLE
Mapping template for max incorrect type?

### ISSUE THREAD

**Issue by ferdy-lw** [stagemonitor/stagemonitor#167]
Is the ES mapping for the max property correct? Currently it's `integer` but shouldn't it be `float` like min? Or vice versa?

https://github.com/stagemonitor/stagemonitor/blob/master/stagemonitor-core/src/main/resources/stagemonitor-elasticsearch-metrics-index-template.json#L29

```
        "max":           { "type": "integer", "doc_values": true, "index": "no" },
        "min":           { "type": "float",   "doc_values": true, "index": "no" }
```

`mean` should probably also be a float.

**Comment by felixbarny** [comment]
You are right about this! `max` and `mean` should also be floats! Do you feel like creating a pull request for that?
