### ISSUE TITLE
AutoEvictingCachingBinaryLocator leaks an Executor on un/redeploy

### ISSUE THREAD

**Issue by elFarto** [stagemonitor/stagemonitor#174]
When attempting to undeploy a webapp that uses Stagemonitor, I'm left with a single thread named "type-pool-cache-evicter". I tracked that down to the AutoEvictingCachingBinaryLocator class, and can see there's no way for it to release that Executor once the application is undeployed. This causes the thread to stick around, and Tomcat to complain loudly:

04-Jul-2016 10:44:06.263 WARNING [http-nio-8079-exec-5] org.apache.catalina.loader.WebappClassLoaderBase.clearReferencesThreads The web application [WebApp] appears to have started a thread named [type-pool-cache-evicter] but has failed to stop it. This is very likely to create a memory leak. Stack trace of thread:
 sun.misc.Unsafe.park(Native Method)
 java.util.concurrent.locks.LockSupport.parkNanos(LockSupport.java:226)
 java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.awaitNanos(AbstractQueuedSynchronizer.java:2082)
 java.util.concurrent.ScheduledThreadPoolExecutor$DelayedWorkQueue.take(ScheduledThreadPoolExecutor.java:1090)
 java.util.concurrent.ScheduledThreadPoolExecutor$DelayedWorkQueue.take(ScheduledThreadPoolExecutor.java:807)
 java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1068)
 java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
 java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
 java.lang.Thread.run(Thread.java:745)

**Comment by felixbarny** [comment]
Thanks for reporting!
