### ISSUE TITLE
Stagemonitor doesn't initalise when stagemonitor.instanceName is null

### ISSUE THREAD

**Issue by elFarto** [stagemonitor/stagemonitor#175]
The documentation claims that stagemonitor.instanceName can be null and that when it is, the name will be auto-detected. However, the MeasurementSession.isInitialized() method requires instanceName to be non-null. If it is null, the Stagemonitor.doStartMonitoring() method won't call start().

I'm not sure what the fix is here, but I'd rather not have a configuration file per-node just to set the hostname of the machine it's running on.

**Comment by felixbarny** [comment]
It's right that monitoring does not start unless the instance name is determined. But when executing the first request against your application, the instance name is auto detected, if possible: https://github.com/stagemonitor/stagemonitor/blob/5b356bb47c369babb73548a32566abd65852011d/stagemonitor-requestmonitor/src/main/java/org/stagemonitor/requestmonitor/RequestMonitor.java#L197-L197

After that, the monitoring ist starting.

**Comment by elFarto** [comment]
Ok, then there is a different issue which I'll raise separately.
