### ISSUE TITLE
Using Stagemonitor in an OSGI application

### ISSUE THREAD

**Issue by domtoupin** [stagemonitor/stagemonitor#181]
Hi,

We are now trying to integrate stagemonitor (more specificaly the stagemonitor-jvm plugin) to monitor our OSGI-based client application. 

I managed to get it to work but I had to hack stagemonitor in order to merge stagemonitor-jvm in it in order for stagemonitor-core to be able to pick up the JvmPlugin class (probably related to the fact that in an OSGI environment, each "bundle" as its own classloader).

Just for the record here are all the manipulations I had to do in order to make it work:
- Created a new stagemonitor-core 0.28.0-SNAPSHOT in which I merged stagemonitor-jvm and install it to my local Maven repo
- Added both org.stagemonitor:stagemonitor-core:0.28.0-SNAPSHOT and io.prometheus:simpleclient:0.0.14 maven dependencies to our main plugin (the latter is needed to resolve the "Import-package: io.prometheus.client" constraint in stagemonitor-core)
- Added the following JVM arguments to resolve osgi.ee constraints and Import-Package constraints on sun.misc and com.sun.management: 
```
-Dorg.osgi.framework.system.capabilities="osgi.ee; osgi.ee=\"JavaSE\";version:List=\"1.6,1.7\""
-Dorg.osgi.framework.system.packages.extra=sun.misc,com.sun.management
```

Can you suggest another way of integrating stagemonitor along with the stagemonitor-jvm plugin that would not require the hack I mentioned above?

**Comment by felixbarny** [comment]
To be honest, I'm not an OSGi expert so I'll have to investigate myself. But I was able to integrate stagemonitor into an Eclipse RCP application, which is OSGi based without any hacks. Actually, the dependency to prometheus is ought to be optional..

What would help is a very basic example application of OSGi + stagemonitor which is easy to start (preferably as easy as `mvn tomcat7:run`) and to debug. 

If you have concrete suggestions on how to improve the OSGi support feel free to create a pull request.

**Comment by domtoupin** [comment]
I was just asking out of curiosity as we are currently moving away from OSGI (our next major version doesN't use OSGI). Since a full OSGI support would benefit only our current installation, I will just close this issue for now and we will proceed with our custom build for our existing installations.
