### ISSUE TITLE
Reporters convert every histogram property into a duration

### ISSUE THREAD

**Issue by captSL** [stagemonitor/stagemonitor#184]
It seems that when reporting a histogram the reporter classes convert all properties of the histogram from nanoseconds to milliseconds. This is ok for the histogram of a timer but when you use a histogram metric to measure something else this leads to wrong results. 

For example when using a histogram to track the distribution of the response size of a servlet request the value to track would be the number of bytes, not duration.

**Comment by felixbarny** [comment]
Maybe the right way is to not convert durations on histograms as if you want durations in a histogram, why not use timer so its probably safe to assume histograms don't have to be converted. 

The workaround for now would be to multiply the number of bytes with 1,000,000.
