### ISSUE TITLE
Host and Logging not showing in Grafana

### ISSUE THREAD

**Issue by gearlles** [stagemonitor/stagemonitor#194]
I just installed stagemonitor and grafana + elastic using the `docker-compose.yml` provided in the wiki. Everything works fine, except that there are no host and logging dashboards in Grafana, although the documentation and the [plugin](https://grafana.net/plugins/stagemonitor-elasticsearch-app) page state that they exist:

## Host
![hosts](https://cloud.githubusercontent.com/assets/4605206/18131905/fbae2910-6f6a-11e6-9466-6a1fea75d4da.png)

## Logging
![dashboard-logging-ced456f7](https://cloud.githubusercontent.com/assets/4605206/18131939/10cf3244-6f6b-11e6-984d-99226b07f34c.png)

I enabled debug logs and there are no exceptions, errors or unexpected behavior. Do I need to set any proprety to enable these metrics?

**Comment by felixbarny** [comment]
Hi,
thanks for you question. This is indeed a bit unclear in the docs so I've updated them. You have to include the corresponding plugins in your application: https://github.com/stagemonitor/stagemonitor/wiki/Step-1:-In-Browser-Widget#include-optional-plugins
