### ISSUE TITLE
Suspicious warning

### ISSUE THREAD

**Issue by domtoupin** [stagemonitor/stagemonitor#198]
Hi,

While monitoring our JBoss 5.1 server using stagemonitor 0.27.2, we came across the following warning:

```
2016-09-09 13:17:35,650 WARN  [org.stagemonitor.core.util.HttpClient] (async-elasticsearch) Error sending POST request to url http://[...]:9200/es/stagemonitor-external-requests-2016.09.09/requests/_bulk: Unexpected character ('<' (code 60)): expected a valid value (number, String, array, object, 'true', 'false' or 'null')
 at [Source: sun.net.www.protocol.http.HttpURLConnection$HttpInputStream@4d331e43; line: 1, column: 2]
```

Is it a known issue? Is there any way to identify the wrong request?

Thank you,

Dominique

**Comment by felixbarny** [comment]
That is indeed strange. Maybe there is a `<` character in one of your sql queries which Elasticsearch does not like. That should not a severe issue as the document will be ignored. In order to reproduce the error I would start searching for `<` chars in your sql, then trigger that sql to see if that's the source of the error.

**Comment by felixbarny** [comment]
Seems like Elasticsearch can handle SQLs containing `<`. So that's probably not the problem. Which Elasticsearch version are you using? Your best bet would be to reproduce the error and to debug what's going wrong.

**Comment by domtoupin** [comment]
We are currently using Elasticsearch 2.3.3; we will try to pinpoint which SQL request was executed when the warning is generated.

Also, just to make sure, your hypothesis would be that some character in the SQL is not properly escaped, thus "corrupting" the JSON sent to Elasticsearch? Is there any way to configure a logger to print the JSON sent by stagemonitor to Elasticsearch?

**Comment by felixbarny** [comment]
> Also, just to make sure, your hypothesis would be that some character in the SQL is not properly escaped, thus "corrupting" the JSON sent to Elasticsearch?

Yes, but that might be wrong as sqls `SELECT * FROM things WHERE 1 < 2` get indexed correctly.

> Is there any way to configure a logger to print the JSON sent by stagemonitor to Elasticsearch?

Currently, there is not. You will have to debug this method: https://github.com/stagemonitor/stagemonitor/blob/7d0d8f625aba65e392df834329ee344be77e4e2d/stagemonitor-requestmonitor/src/main/java/org/stagemonitor/requestmonitor/reporter/ElasticsearchExternalRequestReporter.java#L119-L119

**Comment by domtoupin** [comment]
I did some debugging (I could not reproduce so far in a controlled environment) and I looked at https://github.com/stagemonitor/stagemonitor/blob/master/stagemonitor-core/src/main/java/org/stagemonitor/core/util/HttpClient.java and something struck me: in the `send` method (the one log the message 'Error sending {} request to url...'), only the second exception (`e1`) is logged and the first one `e` is completely discarded. Would it be a good idea to log both exceptions?

Also, I came across http://stackoverflow.com/questions/17206850/resttemplate-getforobject-with-could-not-read-json-unexpected-character-c which seems to state that the issue might be that the error stream might be in XML rather than JSON... Maybe it could be a good idea to add a "logger.trace" to also print the ErrorStream so that even though we might not be able to fix the "parsing" problem, one can try to fix the root problem using the raw stream.

If you want, I can create a PR to implements these two suggestions (I would add them on branch 0.27.x)

Thank you,

Dominique

**Comment by felixbarny** [comment]
Sounds like a plan! But please make a pull request for maser. I can then cherry pick it to 0.27.x if you want. Or you could do two pull requests.

**Comment by domtoupin** [comment]
With a 0.27.3-SNAPSHOT build, we were able to get the following warning:
```
WARN [org.stagemonitor.core.util.HttpClient] (async-elasticsearch) Error sending POST request to url http://[...]:9200/es/stagemonitor-external-requests-2016.09.15/requests/_bulk: Server returned HTTP response code: 413 for URL: http://[...]:9200/es/stagemonitor-external-requests-2016.09.15/requests/_bulk
WARN [org.stagemonitor.core.util.HttpClient] (async-elasticsearch) Error handling error response for POST request to url http://[...]:9200/es/stagemonitor-external-requests-2016.09.15/requests/_bulk: Unexpected character ('<' (code 60)): expected a valid value (number, String, array, object, 'true', 'false' or 'null')
at [Source: sun.net.www.protocol.http.HttpURLConnection$HttpInputStream@12eaa4a3; line: 1, column: 2]
```

I looked up what is a 413 HTTP error and it indicates "Payload too Large" (https://en.wikipedia.org/wiki/List_of_HTTP_status_codes). I checked our Elasticsearch configuration and there is no value for the parameter `http.max_content_length` (https://www.elastic.co/guide/en/elasticsearch/reference/2.3/modules-http.html) thus it indicates that we are using the default 100mb.

We are using the default for `stagemonitor.reporting.interval.elasticsearch` along with the following configurations:
```
stagemonitor.profiler.logCallStacks=true
stagemonitor.elasticsearch.url=http://[...]:9200/es/
stagemonitor.requestmonitor.external.onlyReportNExternalRequestsPerMinute=100000
stagemonitor.requestmonitor.collectExternalRequestTimePerRequest=true
stagemonitor.profiler.objectPooling=true
stagemonitor.profiler.minExecutionTimeNanos=100000
stagemonitor.requestmonitor.elasticsearch.excludeCallTreeFromElasticsearchReportWhenFasterThanXPercentOfRequests=0.00
```

Are we too greedy and really end up with POST requests that can exceed a 100mb?

At this point, I believe there are 4 things that can be done:
1. Modify our stagemonitor configuration to be less greedy but also get less information
2. Modify our stagemonitor configuration to be report to elasticsearch more often
3. Modify our Elasticsearch configuration to allow payload larger than 100mb
4. Modify stagemonitor code to split its payload in smaller chunks

Do you think option 4 is feasible? Also, do you have any recommandation for us to pick the best solution amongst the 3 first choices for now?

**Comment by felixbarny** [comment]
> Are we too greedy and really end up with POST requests that can exceed a 100mb?

If you for example have a lot of SQL statements per request (hundreds or thousands), that can happen. I don't think it makes sense to report all external requests, especially if you have so many. There are several [configuration options](https://github.com/stagemonitor/stagemonitor/wiki/Configuration-Options#options-by-tag) tagged with `external-requests` which allow you to limit the number of reported external requests.

> 2. Modify our stagemonitor configuration to be report to elasticsearch more often

There is no such option. All external requests are reported within a single `/_bulk` request.

> 3. Modify our Elasticsearch configuration to allow payload larger than 100mb

I wouldn't do that. That would overwhelm your es cluster with possibly useless information.

> 4. Modify stagemonitor code to split its payload in smaller chunks

That should be possible to do within stagemonitor, but the proper thing would be to limit what gets reported anyway. So maybe it's best to check for the response code and if it's 413, log a warning that the external request configuration should be reconsidered.

**Comment by felixbarny** [comment]
In the current implementation, there is a configurable limit on the amount of spans in a single bulk request
