### ISSUE TITLE
Custom metrics issues

### ISSUE THREAD

**Issue by gearlles** [stagemonitor/stagemonitor#200]
I'm using stagemonitor (lastest) + elastic + grafana through the `docker-compose.yml` provided in wiki. However, there are two problems: 

1) Custom metrics are not being gathered at all (I just checked on Kibana, there are no entries for `name: timer` and `name: gauge*`). The code has tons of `@Timed` methods being called, though.

2) The custom metrics dashboard is broken. The query filters for `signature` (which I don't know what it is) and breaks the graph:

```
Failed to parse query [name: timer AND application: app AND host: ("host1" OR "host2" OR "host3") AND instance: ("myapp") AND signature: ()]
```

There are no erros on logs, so I'm not attaching them. Please let me know if you need futher information.

**Comment by felixbarny** [comment]
What is your setting for https://github.com/stagemonitor/stagemonitor/wiki/Configuration-Options#included-packages? The signature is the method signature if the @Timed annotated methods.

**Comment by gearlles** [comment]
I pointed to my root package `com.myapp` and the classes with @Timed annotated methods are under this package (e.g. `com.myapp.service.UserService.java`, `com.myapp.controller.UserController.java`).

**Comment by felixbarny** [comment]
Are you annotating interfaces or abstract classes? Could you try to debug whether this methid gehts called: https://github.com/stagemonitor/stagemonitor/blob/master/stagemonitor-core/src/main/java/org/stagemonitor/core/metrics/metrics2/Metric2Registry.java#L149

If not enable [instrumentation debug](https://github.com/stagemonitor/stagemonitor/wiki/Configuration-Options#debug-instrumentation) to see if there is something going wrong in the instrumentation process and if your classes are being transformed at all.

**Comment by gamefundas** [comment]
What is recommended here, annotating the impl class or the interface?

**Comment by felixbarny** [comment]
Annotating the implementation is recommended. Iirc annotating the interface does not work.

**Comment by ratheesh001** [comment]
am facing a similar problem. I am using the standalone application example and using bytebuddy agent using the startup.  I annotated the execute method with @timed annotation. But  i could not see any timers created for my method.

I could see the following metrics printed if i enable elastic logging.

989  [stagemonitor-elasticsearch-reporter] INFO  ElasticsearchMetrics  - {"index":{"_index":"stagemonitor-metrics-2017.04.23","_type":"metrics"}}
{"@timestamp":1492943488000,"name":"online","application":"Test-Standalone-Application","host":"Ratheeshs-MacBook-Pro.local","instance":"test","measurement_start":"1492943487026","value":1.0}
{"index":{"_index":"stagemonitor-metrics-2017.04.23","_type":"metrics"}}
{"@timestamp":1492943488000,"name":"reporting_time","reporter":"log","application":"Test-Standalone-Application","host":"Ratheeshs-MacBook-Pro.local","instance":"test","measurement_start":"1492943487026","count":1,"m1_rate":0.0,"m5_rate":0.0,"m15_rate":0.0,"mean_rate":39.261173808588275,"min":10.014007,"max":10.014007,"mean":10.014007,"p50":10.014007,"std":0.0,"p25":10.014007,"p75":10.014007,"p95":10.014007,"p98":10.014007,"p99":10.014007,"p999":10.014007}

**Comment by ratheesh001** [comment]
The following is my stagemonitor.props and the version is master-SNAPSHOT

`stagemonitor.applicationName=Test Standalone Application
stagemonitor.instanceName=test
stagemonitor.profiler.logCallStacks=true
stagemonitor.internal.monitoring=false
stagemonitor.reporting.interval.console=30
stagemonitor.reporting.elasticsearch.onlyLogElasticsearchMetricReports=true
stagemonitor.reporting.interval.elasticsearch=10
stagemonitor.instrument.include=org.stagemonitor.mytest.task
stagemonitor.instrument.debug=true`

**Comment by felixbarny** [comment]
Did you call `Stagemonitor.init()` at the beginning of the `main` method?

> I am using the standalone application example and using bytebuddy agent using the startup

You mean the `-javaagent` flag? You'll still have to call `Stagemonitor.init()`

**Comment by ratheesh001** [comment]
Thanks felix for the reply. Stagemonitor.init() is the first line of my main method.
The following is the startup log.

`0    [main] INFO  org.stagemonitor.core.Stagemonitor  - Measurement Session is initialized: [application=Test Standalone Application] [instance=test] [host=Ratheeshs-MacBook-Pro.local]
3    [main] INFO  org.stagemonitor.core.Stagemonitor  - Initializing plugin RequestMonitorPlugin
113  [main] INFO  org.stagemonitor.core.Stagemonitor  - Initializing plugin CorePlugin
118  [main] INFO  org.stagemonitor.core.CorePlugin  - Not sending metrics to InfluxDB (url=null, interval=60s)
143  [main] INFO  org.stagemonitor.core.Stagemonitor  - Initializing plugin AlertingPlugin
221  [main] INFO  org.stagemonitor.alerting.AlertingPlugin  - Using ConcurrentMapIncidentRepository for storing incidents.
344  [main] INFO  org.stagemonitor.core.instrument.AgentAttacher  - Registering ProfilingTransformer
346  [main] INFO  org.stagemonitor.core.instrument.AgentAttacher  - Excluding ElasticsearchSearchQueryTransformer
349  [main] INFO  org.stagemonitor.core.instrument.AgentAttacher  - Registering MethodLevelMonitorRequestsTransformer
349  [main] INFO  org.stagemonitor.core.instrument.AgentAttacher  - Registering ClassLevelMonitorRequestsTransformer
350  [main] INFO  org.stagemonitor.core.instrument.AgentAttacher  - Excluding RemoteEjbMonitorTransformer
375  [main] INFO  org.stagemonitor.core.instrument.AgentAttacher  - Registering FreemarkerProfilingTransformer
376  [main] INFO  org.stagemonitor.core.instrument.AgentAttacher  - Registering ExceptionMeteredTransformer
377  [main] INFO  org.stagemonitor.core.instrument.AgentAttacher  - Registering TimedTransformer
377  [main] INFO  org.stagemonitor.core.instrument.AgentAttacher  - Registering MeteredTransformer
378  [main] INFO  org.stagemonitor.core.instrument.AgentAttacher  - Registering GaugeTransformer
379  [main] INFO  org.stagemonitor.core.instrument.AgentAttacher  - Registering SlaCheckCreatingClassPathScanner
940  [main] INFO  org.stagemonitor.core.instrument.AgentAttacher  - Installed agent in 216 ms
940  [main] INFO  org.stagemonitor.core.instrument.AgentAttacher  - Attached agents in 692 ms`

**Comment by felixbarny** [comment]
Ha, thats a cheesy "problem": Your package name is `org.stagemonitor.mytest.task` but in order to exclude stagemonitor from transforming itself, the package `org.stagemonitor` is excluded implicitly. So please choose a different packaging structure.

**Comment by ratheesh001** [comment]
Thanks a lot felix. It worked 👍
