### ISSUE TITLE
Type of profiling approach used in stagemonitor

### ISSUE THREAD

**Issue by sattishv** [stagemonitor/stagemonitor#202]
Hi Team,

We would like to know what kind of an approach was implemented in stagemonitor towards capturing the profiling details. Is it Bytecode instrumentation or sampling or distributed tracing like dapper or ASM profiling.

Thanks
Sattish.

**Comment by felixbarny** [comment]
Stagemonitor uses Byte Buddy to manipulate the bytecode of the instrumented methods to create the call tree. I'm currently working on dapper-like distributed tracing.
