### ISSUE TITLE
Stagemonitor stops application processing in case it is not able to dispatch metrics to ES.

### ISSUE THREAD

**Issue by get2parag** [stagemonitor/stagemonitor#208]
Hi,
This is pretty weird but we have noticed this on quite a few occasions now that if stagemonitor is not able to dispatch metircs to ES or if the request processing queue capacity is full the application itself stops processing any incoming request. I understand that stagemonitor processes these requests in a separate thread deamon thread however the application failures are pretty consistent with the SM request rejections.

Stagemonitor rejects the task with following logs:-

```
2016-10-18 18:39:40,977 WARN  [async-request-reporter] org.stagemonitor.core.util.ExecutorUtils |                       | - The limit of pending tasks for the executor is reached. This could be due to a unreachable service such as elasticsearch or due to a spike in incoming requests. Consider increasing the default capacity limit with the configuration key 'stagemonitor.threadPools.queueCapacityLimit'
Task java.util.concurrent.FutureTask@6198b7f rejected from org.stagemonitor.core.util.ExecutorUtils$1@3d3e9656[Running, pool size = 1, active threads = 1, queued tasks = 10000, completed tasks = 525](thread name = async-elasticsearch)
```

And in conjunction the application also rejects any incoming request. Currently I'm trying to replicate this scenario on my local and will update if I find any direct correlation. 

Any pointers here will be greatly appreciated.
Details about the environment:-
Sprint boot application with v 1.3.5, embedded undertow container deployed on EC2 machine AWS. SM queue capacity size = 10000. StageMonitor version 0.25.0

**Comment by felixbarny** [comment]
Hi,
I can't think of a situation where stagemonitor blocks the request execution because of Elasticsearch being not available. Could it be possible that this is caused by network problems which lead to Elasticsearch being not available and additionally block your application when it's trying to connect to a external service? It would be helpful to analyze a thread dump when this situation occurs. In that we could see where (and hopefully why) the threads block. 

If this turns out to be a problem within stagemonitor, I will of course fix it with a high priority.

**Comment by get2parag** [comment]
I'll try to get back with some concrete proof here. However will be happy if proven otherwise.

**Comment by gamefundas** [comment]
After tons of the following error in logs, the application ends up with OOM. The application is running as a cluster and we saw both the nodes fail with similar errors.

org.stagemonitor.core.util.ExecutorUtils - The limit of pending tasks for the executor is reached. This could be due to a unreachable service such as elasticsearch or due to a spike in incoming requests. Consider increasing the default capacity limit with the configuration key 'stagemonitor.threadPools.queueCapacityLimit'

Probably its not blocking anything but is holding a lot information in memory that couldn't be flushed to ES. ES wasn't available at this time, which is a known issue but we didn't think the application would be impacted by this.

**Comment by felixbarny** [comment]
Thx for the info. I can see that you have increased the queue capacity to 10000. That might be too much and almost fills your heap. How big is your heap and what are your other settings for stagemonitor? Is the profiler active? Do you monitor external requests?

**Comment by felixbarny** [comment]
I'll probably add a check if es is available. If not, the request trace won't be handed over to the es reporter.

**Comment by felixbarny** [comment]
I've added the availability check. Could you try out my changes? This is how you build a snapshot:

```
git clone https://github.com/stagemonitor/stagemonitor.git
cd stagemonitor
git checkout es-availability-check
./gradlew install
```

This installs 0.29.0-SNAPSHOT into your local maven repo (`~/.m2/repository/org/stagemonitor `)

**Comment by gamefundas** [comment]
Thanks for the quick fix. We will give this a try and get back on this thread.

**Comment by felixbarny** [comment]
As soon as I get your feedback I can release a new version.

**Comment by get2parag** [comment]
My apologies for not replying on this earlier. Earlier had few SSH certificate issues while connecting to repo however managed a workaround.

Will update this in couple of hours. 

Also may I request you to include a fix for https://github.com/stagemonitor/stagemonitor/issues/93 in the next release for SM.

**Comment by get2parag** [comment]
The fix seems to be working. i can see following logs:-
`2016-11-03 11:39:59,766 WARN  [elasticsearch-tasks] org.stagemonitor.core.elasticsearch.ElasticsearchClient |	 		| - Elasticsearch is not available. Stagemonitor won't try to send request traces to Elasticsearch until it is available again.`

However I noticed following exception as well :-`2016-11-03 11:41:00,005 ERROR [stagemonitor-elasticsearch-reporter] org.stagemonitor.core.metrics.metrics2.ScheduledMetrics2Reporter |	 		| - RuntimeException thrown from #report. Exception was suppressed.
java.lang.NullPointerException: null
	at org.stagemonitor.core.elasticsearch.ElasticsearchClient$BulkErrorReportingResponseHandler.handleResponse(ElasticsearchClient.java:336)
	at org.stagemonitor.core.elasticsearch.ElasticsearchClient$BulkErrorReportingResponseHandler.handleResponse(ElasticsearchClient.java:329)
	at org.stagemonitor.core.util.HttpClient.send(HttpClient.java:103)
	at org.stagemonitor.core.metrics.metrics2.ElasticsearchReporter.reportMetrics(ElasticsearchReporter.java:68)
	at org.stagemonitor.core.metrics.metrics2.ScheduledMetrics2Reporter.report(ScheduledMetrics2Reporter.java:45)
	at org.stagemonitor.core.metrics.metrics2.ScheduledMetrics2Reporter$1.run(ScheduledMetrics2Reporter.java:101)
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
	at java.util.concurrent.FutureTask.runAndReset(Unknown Source)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(Unknown Source)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)`

Apparently bulkresponse or errors inside it are null :)

**Comment by gamefundas** [comment]
@felixbarny should we assume the NPE is also handled. Pardon me if I missed seeing your comment about that. 

Thanks for the fix. Looking forward to enable SM now in our stacks.

**Comment by felixbarny** [comment]
I'm currently fixing the NPE. EhCache 2.7+ support will however not be included in this release.

**Comment by felixbarny** [comment]
Stagemonitor 0.29.0 is released. Happy monitoring :)
