### ISSUE TITLE
Why use `Avg aggregation` for slowest-queries-p75?

### ISSUE THREAD

**Issue by Jack47** [stagemonitor/stagemonitor#211]
I found that the [Slowest-Queries-P75](https://github.com/stagemonitor/stagemonitor/blob/master/stagemonitor-jdbc/src/main/resources/kibana/JdbcDashboard.bulk#L15) displayed in kibana are using `avg aggregation`. Why don't you use `Mean`? Is there any reference that support you to use `avg aggregation`?

**Comment by felixbarny** [comment]
Why would mean be better?

**Comment by curlup** [comment]
Hi
There's no true way to aggregate percentiles. 
More info [here](http://math.stackexchange.com/questions/423535/way-to-aggregated-percentiles) and [here](http://www.lmgtfy.com/?q=Gil+Tene+average+percentiles)

One way to try not to mislead with that chart would be to use `max aggregation` - at least it wouldn't be sugar-coating. Though in some cases it might show you too aggravated values.

**Comment by felixbarny** [comment]
> There's no true way to aggregate percentiles.

Thats true.

Actually the charts use the n-th percentile of the n-th percentile. That means that the p75 percentile is not aggregated by the average but by the p75 percentile. This at least leads to a "less wrong" aggregation.
