### ISSUE TITLE
onlyLogElasticsearchMetricReports and no Elasticsearch access

### ISSUE THREAD

**Issue by elFarto** [stagemonitor/stagemonitor#214]
I've run across an issue where, due to the environment setup, my application will not be allowed direct access to Elasticsearch, and all logging must be done via Logstash. I've managed to use onlyLogElasticsearchMetricReports and co. to route everything through a logstash appender, and configured logstash to work appropriately. However, Stagemonitor will not start the ElasticsearchReporter if no Elasticsearch URL is specified.

Would it be a problem if it Elasticsearch logging was enabled if onlyLogElasticsearchMetricReports and co. were set to true. Obviously the template creation, index management and kibana dashboard parts would be disabled, but they can be managed externally.

I'm working on a patch for it, I just wanted to get your thoughts on the matter as I've noticed some extra checks for seeing if Elasticsearch is up.

**Comment by felixbarny** [comment]
> Would it be a problem if it Elasticsearch logging was enabled if onlyLogElasticsearchMetricReports and co. were set to true

This would be the desired behaviour.

> I'm working on a patch for it, I just wanted to get your thoughts on the matter as I've noticed some extra checks for seeing if Elasticsearch is up.

That's awesome. I'd be more than happy to merge such a pull request. Obviously, the check if ES is available would only apply in case onlyLogElasticsearchMetricReports is false.

**Comment by elFarto** [comment]
Issue fixed in 0.30
