### ISSUE TITLE
elasticsearch indexes names and *-index-template.json documentation

### ISSUE THREAD

**Issue by Camts** [stagemonitor/stagemonitor#217]
**What I want to do**: use different elasticsearch indexes depending on environment (`dev`, `qal`, `prod`). For example `stage-monitor-dev-*`
**Test**: put a copy of `stagemonitor-elasticsearch-metrics-index-template.json` file from `stagemonitor-core-0.29.1.jar` into `src/main/resources` of my project, and modify value of first property named `template`
**Result**: no change

After a quick source code analysis, this can not be configured, since it uses `ElasticsearchReporter.STAGEMONITOR_METRICS_INDEX_PREFIX` constant.
But `Configuration-Options` wiki page says "you can fully customize the index template".

I have not found in wiki a description of `stagedmonitor-elasticsearch-*-index-template.json` files (`metrics`, `request`, `external-requests`...): structure and meaning of each property

**Comment by felixbarny** [comment]
The index name itself cant be modified. There are no plans to support that. I understand your use case and its perfectly valid. But rather than having different index name patterns I would suggest to have a different elasticsearch cluster for test and prod.

**Comment by Camts** [comment]
Thank you for quick response.
