### ISSUE TITLE
ElasticSearch availability check does not works if ElasticSearch is configured to answer to an URL ending with a "/"

### ISSUE THREAD

**Issue by domtoupin** [stagemonitor/stagemonitor#220]
## Setup

Component | Version
-------- | ----
Wildfly | 10.1.0
Java | Java(TM) SE Runtime Environment (build 1.8.0_101-b13)
Stagemonitor | 0.30.0

## Context

Our ElasticSearch configuration is currently a three part setup; an nginx server upfront, with a kopf server to monitor our elasticsearch cluster answer directly at the root of the nginx server and our elasticsearch servers answering at "/es/".

The problem is that the trailing "/" is removed from the elasticsearch urls (see CorePlugin::getElasticsearchUrl()) and the "HEAD" request sent by ElasticSearchClient.CheckEsAvailability always end up in a 400 response. I managed to bypass this issue by doubling the trailing "/" but that is clearly a workaround...

**Comment by felixbarny** [comment]
Its not only a workaround. Stagemonitor relies on the URL to not end with a slash because paths like /_bulk are appended which would otherwise lead to double slashes (/es//bulk). I think the proper solution would be to configure nginx to also forward /es to your Elasticsearch server.

**Comment by felixbarny** [comment]
What probably would also work is that i append a slash for the availability check. That should also work for direct access like http://localhost:9200/

**Comment by domtoupin** [comment]
@felixbarny I just tried the fix and it works perfectly for us. Thank you for the super quick resolution!

**Comment by felixbarny** [comment]
You're welcome. Do you need a bugfix release?

**Comment by domtoupin** [comment]
That would be much appreciated.
