### ISSUE TITLE
Application server dashboard is "empty"

### ISSUE THREAD

**Issue by yacota** [stagemonitor/stagemonitor#226]
Although servers are there, their metrics are always 0
![snapshot](https://cloud.githubusercontent.com/assets/2678582/21106837/e34c8ae4-c08f-11e6-9429-a38510a96f36.jpg)

I've reviewed the documentation available at https://github.com/stagemonitor/stagemonitor/wiki/Configuration-Options and dashboard metrics does not seem to need any special config in order to work properly

We are using Tomcat-8.5.x 

By the way, I was expecting to see the Tomcat thread pool usage in this dashboard :), something like https://github.com/stagemonitor/stagemonitor/wiki/Server-Dashboard

**Comment by felixbarny** [comment]
The screenshot seems to indicate that Grafana does show the thread pool usage, it's just quite low.

**Comment by yacota** [comment]
Actually those servers work pretty well, but not that much :)
Let's see, maybe I am wrong ... but I am expecting to see Tomcat's thread pool usage, which in turn has direct relation with how many  "maxThreads" are defined in Tomcat's conf/server.xml file

**Comment by felixbarny** [comment]
The dashboard only shows the usage (in percent iirc) not the total amount of threads.

**Comment by gamefundas** [comment]
@felixbarny is this support limited only to Tomcat containers. I see empty Application dashboard In my case too but then we are using Undertow in our Spring boot apps.

**Comment by felixbarny** [comment]
Yes, at the moment this only supports Tomcat as every Application Server reports the state of the thread pool differently.

**Comment by yacota** [comment]
I just want to confirm that the dashboard works fine.
I've created a sample project that runs into Tomcat 8.0.x and 8.5.x and measured the behaviour with JMeter, and it just works as expected. 
So it seems that the app performs much better than what I was expecting :)
Sorry and thanks @felixbarny
