### ISSUE TITLE
How to give credentials for ES stagemonitor?

### ISSUE THREAD

**Issue by gopinath-evive** [stagemonitor/stagemonitor#230]
I am getting below warn and error when stagemonitor is trying to enter data in the ES.

> 20 Dec 2016 19:59:28,845  WARN  [I/O dispatcher 3] LoggingBulk:120 - [] - [] - Error in parsing responseBody as JSON: <!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
> <html><head>
> <title>401 Unauthorized</title>
> This server could not verify that you
> are authorized to access the document
> requested.  Either you supplied the wrong
> credentials (e.g., bad password), or your
> browser doesn't understand how to supply
> the credentials required.

> 20 Dec 2016 19:59:28,845 ERROR  [I/O dispatcher 3] ElasticsearchReporter:128 - [] - [] - BulkRequest to ElasticSearch had failures. Reason: 401 Unauthorized
> 

This ES cluster needs username and password to use it.
But how to do give this through the properties file or any other config file?

**Comment by felixbarny** [comment]
See #223
I'll try to release this tomorrow.

**Comment by felixbarny** [comment]
Stagemonitor 0.31.0 is now available on maven central. Happy monitoring!
