### ISSUE TITLE
Method Call Trace in case of a spring boot app

### ISSUE THREAD

**Issue by Xhings** [stagemonitor/stagemonitor#234]
Hi 
Thanks for creating Stagemonitor! I really helps getting fine grained details. 

I am evaluating Stage monitor for gathering metrics from our Spring Boot app. We have micro-services environment and I can get the build in dashboards like Calls per sec/method invocation time spent for two sample services speaking to each other. How to get method call tree in case of a service to service call similar to the Call Tree widget in the demo app? Ours is a non UI App env.

Cheers!

**Comment by felixbarny** [comment]
Currently, you will have to look up the call tree in Kibana, which contains the call tree rendered as ascii art. See also https://github.com/stagemonitor/stagemonitor/wiki/Request-Analysis-Dashboard.
