### ISSUE TITLE
Not working with elastic 5.1.1 

### ISSUE THREAD

**Issue by letshelp** [stagemonitor/stagemonitor#235]
Just plugged spring boot app with version 0.31.0 of stagemonitor. Pointing to elastic 5.1.1 but having only following data point.
{
"_index": "stagemonitor-metrics-2017.01.12",
"_type": "metrics",
"_id": "AVmThYwzpJc4-DsOMUu8",
"_score": 1
}
No application,host,instance and other meta data that are required at grafana dashboard loading time hence receiving
"Templating init failed
[object Object]" error on dashboard.

-Jet

**Comment by felixbarny** [comment]
Hi,

the data point actually looks like expected. The [Elasticsearch mapping](https://github.com/stagemonitor/stagemonitor/blob/master/stagemonitor-core/src/main/resources/stagemonitor-elasticsearch-metrics-index-template.json) is configured so that the `_source` field is not stored. See https://www.elastic.co/blog/elasticsearch-as-a-time-series-data-store "First Stop: Mappings" for more info.

Which Version of Grafana are you using? Could you look in the developer console if there is more information about the error?

**Comment by letshelp** [comment]
I am using grafana-4.0.2. It's working fine when I am using elastic 2.2. Here is the req/res when it makes call to es for application name on dashboard loading. (I tried to upload file but failed :( so keeping it inline)

Query String Parameters
search_type:count

Request Payload
{"search_type":"count","ignore_unavailable":true,"index":["stagemonitor-metrics-2017.01.12"]}
{"size":0,"query":{"filtered":{"filter":{"bool":{"must":[{"range":{"@timestamp":{"gte":"1484248017521",
"lte":"1484251617521","format":"epoch_millis"}}}]}},"query":{"query_string":{"analyze_wildcard":true,"query":"*"}}}},
"aggs":{"1":{"terms":{"field":"application","size":0,"order":{"_term":"asc"}}}}}

Response 
{"error":{"root_cause":[{"type":"illegal_argument_exception","reason":"No search type for [count]"}],
"type":"illegal_argument_exception","reason":"No search type for [count]"},"status":400}

General
Request URL:http://localhost:3000/api/datasources/proxy/3/_msearch?search_type=count
Request Method:POST
Status Code:400 Bad Request
Remote Address:[::1]:3000

Response Header
Access-Control-Allow-Origin:*
Content-Encoding:gzip
Content-Length:131
Content-Type:application/json; charset=UTF-8
Date:Thu, 12 Jan 2017 20:06:57 GMT
Request Headers
Access-Control-Allow-Origin:*
Content-Encoding:gzip
Content-Length:131
Content-Type:application/json; charset=UTF-8
Date:Thu, 12 Jan 2017 20:06:57 GMT

**Comment by felixbarny** [comment]
I just found out that you have to set the version to 5.x in the datasource configuration.
 
![grafana-es-5](https://cloud.githubusercontent.com/assets/2163464/21933999/07cb1760-d9a8-11e6-9481-a42aa6e75dd1.png)

**Comment by letshelp** [comment]
What is your grafana version? I just tried with 4.1.1 but don't see 5.x in version.

**Comment by felixbarny** [comment]
Hm, that's strange. I'm also using 4.1.1. I go to Menu > Data Sources > ES stagemonitor > Elasticsearch Details > Version > 5.x.

The bottom on the page says `Grafana v4.1.1 (commit: v4.1.1)`.

**Comment by letshelp** [comment]
No luck yet. Tried with 4.1.1 and 4.1.0. 
What's your OS?

**Comment by felixbarny** [comment]
I use the Grafana docker container with Docker for mac (macOS 10.12.2).

**Comment by letshelp** [comment]
Thanks for help felix. It seems that latest grafana's windows binary is having issue.
