### ISSUE TITLE
Is it possible to avoid Browser Widget

### ISSUE THREAD

**Issue by JEnIUS85** [stagemonitor/stagemonitor#244]
hi,
Can i use stagemonitoring without the Browser Widget. 
i short, APM monitoring captures all the live request and push to influx db but without showing browser widget on the web page?

**Comment by felixbarny** [comment]
Sure. see https://github.com/stagemonitor/stagemonitor/wiki/Configuration-Options#in-browser-widget-enabled

Also, this guide might be interesting for you: https://github.com/stagemonitor/stagemonitor/wiki/How-should-I-configure-stagemonitor%3F
