### ISSUE TITLE
Application Topology Discovery

### ISSUE THREAD

**Issue by JEnIUS85** [stagemonitor/stagemonitor#245]
Hi,

i am looking for a dashboard where the complete topology (Software and hardware infrastructure component involved in an application execution) is displayed.  it helps to visualize how different components/servers are communicating in my application stack.

Does stagemonitor helps in auto discovery of application topology?

I am not sure if "Discover" option in Kibana dashboard does exactly what i am looking for. Kindly help

**Comment by felixbarny** [comment]
Hi,

first of all, this requires distributed tracing (#118), which I'm currently actively working on. There are no plans in the near future to implement a topology map. However, reporting to [zipkin](http://zipkin.io) will be possible which has this feature.

**Comment by JEnIUS85** [comment]
thanks Felixbarny ..
