### ISSUE TITLE
Support for Servlet based application hosted on famous application servers

### ISSUE THREAD

**Issue by JEnIUS85** [stagemonitor/stagemonitor#246]
Hi Felixbarny,

You have been very supportive in answering my queries so far. thx a lot.

One more query i have that needs your input..

I see on wiki the steps to monitor "non-servlet" applications. My query is if there is an inbuilt support to monitor servlet based application hosted on following servers with zero or minimal configuration. Kindly let me know if any configuration changes has to be made:

Tomcat, Jetty, JBoss, WebLogic, GlassFish and Websphere.

Nitin.

**Comment by felixbarny** [comment]
Yes, there is. That is one of the main features of stagemonitor. It's currently tested with Tomcat, Jetty, JBoss. Others should work as well. Just follow the normal installation guide: https://github.com/stagemonitor/stagemonitor/wiki/Step-1%3A-In-Browser-Widget. Feel free to comment on this issue if you have further questions on the installation process :)
