### ISSUE TITLE
grafana plugin statemonitor error?

### ISSUE THREAD

**Issue by songlong** [stagemonitor/stagemonitor#248]
kibana 5.2
elasticsearch: 5.2
java : 1.8 

 Request Metrics 
Zoom Out
 Last 1 hour   Refresh every 30s
Application
None 
Host
All 
Instance
All 
Request
None 
Time
Server 
 Documentation (click me to expand)
 Collapse
 Add Panel
 Row Options
 Move Up
 Move Down
 Remove
Response Time
16:1016:1516:2016:2516:3016:3516:4016:4516:5016:5517:0017:050 ms1.0 ms10.0 ms
Throughput by Status
16:1016:1516:2016:2516:3016:3516:4016:4516:5016:5517:0017:0500.20.40.60.81.0
 Collapse
 Add Panel
 Row Options
 Move Up
 Move Down
 Remove
Slowest Requests (Median)
16:1016:1516:2016:2516:3016:3516:4016:4516:5016:5517:0017:050 ms0.2 ms0.4 ms0.6 ms0.8 ms1.0 ms
min	max	avg	current
Highest Throughput
16:1016:1516:2016:2516:3016:3516:4016:4516:5016:5517:0017:0500.20.40.60.81.0
min	max	avg	current
 Collapse
 Add Panel
 Row Options
 Move Up
 Move Down
 Remove
Slowest Requests (p95)
16:1016:1516:2016:2516:3016:3516:4016:4516:5016:5517:0017:050 ms0.2 ms0.4 ms0.6 ms0.8 ms1.0 ms
min	max	avg	current
Most Errors
16:1016:1516:2016:2516:3016:3516:4016:4516:5016:5517:0017:0500.20.40.60.81.0
min	max	avg	current
 Collapse
 Add Panel
 Row Options
 Move Up
 Move Down
 Remove
Page Load Time Breakdown
16:1016:1516:2016:2516:3016:3516:4016:4516:5016:5517:0017:050 ms0.2 ms0.4 ms0.6 ms0.8 ms1.0 ms
Empty Space
 ADD ROW
 Inspector
Panel Description
Request
Response
JS Error
{
    "root_cause": [
        {
            "type": "query_shard_exception",
            "reason": "Failed to parse query [name: response_time_server AND layer: All AND !request_name: All AND application:  AND host: () AND instance: ()]",
            "index_uuid": "MSmCPp-TTGG4RC0SYhgs2g",
            "index": "metricbeat-2017.02.16"
        }
    ],
    "type": "search_phase_execution_exception",
    "reason": "all shards failed",
    "phase": "query",
    "grouped": true,
    "failed_shards": [
        {
            "shard": 0,
            "index": "metricbeat-2017.02.16",
            "node": "-n5gK3nhRl-uO2_OGxNNjQ",
            "reason": {
                "type": "query_shard_exception",
                "reason": "Failed to parse query [name: response_time_server AND layer: All AND !request_name: All AND application:  AND host: () AND instance: ()]",
                "index_uuid": "MSmCPp-TTGG4RC0SYhgs2g",
                "index": "metricbeat-2017.02.16",
                "caused_by": {
                    "type": "parse_exception",
                    "reason": "Cannot parse 'name: response_time_server AND layer: All AND !request_name: All AND application:  AND host: () AND instance: ()': Encountered \"  \"AND \"\" at line 1, column 83.\nWas expecting one of:\n     ...\n    \"(\" ...\n    \"*\" ...\n     ...\n     ...\n     ...\n     ...\n     ...\n    \"[\" ...\n    \"{\" ...\n     ...\n    ",
                    "caused_by": {
                        "type": "parse_exception",
                        "reason": "Encountered \"  \"AND \"\" at line 1, column 83.\nWas expecting one of:\n     ...\n    \"(\" ...\n    \"*\" ...\n     ...\n     ...\n     ...\n     ...\n     ...\n    \"[\" ...\n    \"{\" ...\n     ...\n    "
                    }
                }
            }
        }
    ],
    "caused_by": {
        "type": "query_shard_exception",
        "reason": "Failed to parse query [name: response_time_server AND layer: All AND !request_name: All AND application:  AND host: () AND instance: ()]",
        "index_uuid": "MSmCPp-TTGG4RC0SYhgs2g",
        "index": "metricbeat-2017.02.16",
        "caused_by": {
            "type": "parse_exception",
            "reason": "Cannot parse 'name: response_time_server AND layer: All AND !request_name: All AND application:  AND host: () AND instance: ()': Encountered \"  \"AND \"\" at line 1, column 83.\nWas expecting one of:\n     ...\n    \"(\" ...\n    \"*\" ...\n     ...\n     ...\n     ...\n     ...\n     ...\n    \"[\" ...\n    \"{\" ...\n     ...\n    ",
            "caused_by": {
                "type": "parse_exception",
                "reason": "Encountered \"  \"AND \"\" at line 1, column 83.\nWas expecting one of:\n     ...\n    \"(\" ...\n    \"*\" ...\n     ...\n     ...\n     ...\n     ...\n     ...\n    \"[\" ...\n    \"{\" ...\n     ...\n    "
            }
        }
    }
}

**Comment by felixbarny** [comment]
I can see that you are not using the stagemonitor-metrics-* index but `metricbeat-2017.02.16`. The problem is that the dashboard can't find values for the `application`, `host` and `instance` template variables.

**Comment by songlong** [comment]
en, yes
but how to import data for stagemonitor-metrics-*

**Comment by felixbarny** [comment]
Stagemonitor is an agent you have to include in your Java application which sends metrics to a TSDB. 

So in order to see metrics in the dashboard, you first have to install stagemonitor.

In which dashbaords are you particularly interested in?

**Comment by songlong** [comment]
intersteting jvm 
collect jvm metrics and analyze my java appplication performance
my centos server had installed jvm.
I need config my java agent?

**Comment by felixbarny** [comment]
The wiki contains a installation guide which explains all the steps :)
