### ISSUE TITLE
Being able to include paths that need to contain the call tree (for common requests that are not the slowest ones)

### ISSUE THREAD

**Issue by yacota** [stagemonitor/stagemonitor#251]
Sometimes you need the call tree for some kind of requests which are not the slowest ones BUT they are quite common, for this reason I think that it would be handy if we could specify a property that will inform StageMonitor that for some requests, maybe matched using a regex(?) , the call tree needs to be stored.
I think that this feature will/could someway "interferee" with 

https://github.com/stagemonitor/stagemonitor/wiki/Configuration-Options#min-execution-time-nanos and https://github.com/stagemonitor/stagemonitor/wiki/Configuration-Options#min-execution-time-
https://github.com/stagemonitor/stagemonitor/wiki/Configuration-Options#only-report-n-requests-per-minute-to-es
https://github.com/stagemonitor/stagemonitor/wiki/Configuration-Options#exclude-the-call-tree-from-elasticsearch-reports-on-x-of-the-fastest-requests
https://github.com/stagemonitor/stagemonitor/wiki/Configuration-Options#only-report-n-call-trees-per-minute

But I think that it would be extremely useful

**Comment by felixbarny** [comment]
Hi and thx for the request.

the current problem is that `RequestMonitor#isProfileThisRequest` is not very extendible and that you can only exclude call trees via `PostExecutionInterceptorContext#addExcludedProperties`.

I think it would make most sense to add the methods `PreExecutionInterceptorContext#shouldNotCollectCallTree` and `PreExecutionInterceptorContext#mustCollectCallTree`. If you've got a suggestion for a better naming please go ahead :)

**Comment by felixbarny** [comment]
One problem with you use case is that the request name might not have been determined at the time stagemonitor makes the decision whether or not to activate the profiler (collect the call tree).

**Comment by yacota** [comment]
Thanks @felixbarny ,  and sorry because I did not have time to work/collaborate in this issue

**Comment by felixbarny** [comment]
np :)
