### ISSUE TITLE
Demo appears to be default Spring Framework site

### ISSUE THREAD

**Issue by mrmanc** [stagemonitor/stagemonitor#256]
Apologies if it is intentional, but I clicked the demo and it appears to be a default Spring Framework demo site. I was expecting a demo of stagemonitor itself, so thought I’d raise this.

https://stagemonitor-demo.isys-software.de/

**Comment by felixbarny** [comment]
You have to klick on the icon on the bottom right to see the magic ;)

**Comment by mrmanc** [comment]
Oh no… how embarrassing. Apologies—I’m sorry to have wasted your time! :)

**Comment by felixbarny** [comment]
Np ;). You are not the only one though. I should probably add an arrow pionting to the icon.
