### ISSUE TITLE
Custom name for @timed

### ISSUE THREAD

**Issue by ratheesh001** [stagemonitor/stagemonitor#261]
In the below example, i need to pass the value of queryName as the name of Timed, as i need to capture the timings of different queries

```
public class MyPreparedStatement {

	private String queryName;

	@Timed(name=queryName)
	public void executeQuery(){
		try {
			long start = System.currentTimeMillis();
			Thread.sleep(1000);
			System.out.println("completed executeQuery");	
		} catch (InterruptedException e) {
			e.printStackTrace();
		}
	}

```
Is it possible?

**Comment by felixbarny** [comment]
The value of annotations has to be a constant so this is not possible in Java. One way to work around this would be to use an expression language but stagemonitor does not support that. So you'd have to add the timer manually which is not a lot of effort either. See https://github.com/stagemonitor/stagemonitor/wiki/Track-your-own-metrics#programmatic

But it seems like you want to track the execution time of a JDBC statement. The stagemonitor-jdbc library does that automatically. The name of the timer would then be `ClassName#methodName`.


```

**Comment by mahileeb** [comment]
@felixbarny Is there away to provide more detail to the jdbc plugin? Most of our queries go through a common query execute/stream layer so the metric name is the same on all queries e.g. "QueryStreamer#lambda$doQuery$2"
