### ISSUE TITLE
Is Stagemonitor 0.31.0 supports Elasticsearch 5.4.x?

### ISSUE THREAD

**Issue by Unlocker** [stagemonitor/stagemonitor#263]
I have done a little investigation with integration between Stagemonitor 0.31.0 and Elasticsearch 5.4.0 (Docker image **sebp/elk:5.4.0**). I have seen some issues with indices and visualizations:

1. For example, index pattern " [stagemonitor-metrics-]YYYY.MM.DD" bulk script contains 46 fields but imported pattern contains 41 fields.
1. Another index pattern "[stagemonitor-requests-]YYYY.MM.DD" defines 60 fields but imported pattern contains only 50 fields.
1. Opened dashboard "Application Server" is broken with error "Error: [parsing_exception] [terms] failed to parse field [size], with { line=1 & col=463 }". I propose that relates with broken patterns.

Is anybody has an experience for fixing provided issues?

**Comment by Unlocker** [comment]
I read the partition "Breaking Changes" both in ElasticSearch and Kibana documentation. 
I have downgraded my service to **sebp/elk:es241_l240_k461** for a several time. It takes some time to replace old index and template sources with the new ones.

@felixbarny, are you going to support migration from ES 2.x to 5.x?

**Comment by felixbarny** [comment]
Stagemonitor 0.31.0 is not compatible with Kibana v4. However, the upcoming stagemonitor 0.80.0 will require ES 5.x and Kibana 5.x

**Comment by felixbarny** [comment]
P.S.: sorry for the delay

**Comment by Unlocker** [comment]
@felixbarny, thank you for the reply. It is OK. I will wait until new version released.
