### ISSUE TITLE
Can stagemonitor work with Jboss without changing any source code

### ISSUE THREAD

**Issue by njufrog** [stagemonitor/stagemonitor#264]
I want to use stagemonitor to monitor my web base Jave project. I'm using Jboss as the container. My source code was packaged as WAR and deployed in Jboss. In the wiki, it says I need to unpack my WAR, and include stagemonitor jar in the lib; or change my pom.xml.

So I wonder if there is a method that I can use stagemonitor, but not change any of the source code? Is it possible?

**Comment by felixbarny** [comment]
Hi and thanks for your question,

You probably mean if stagemonitor supports being registered via a `-javaagent`? This is currently not possible. See the [FAQ wiki site](https://github.com/stagemonitor/stagemonitor/wiki/FAQs#is-there-a-way-to-configure-stagemonitor-via--javaagent).

Why is changing the `pom.xml` a problem in your case?
