### ISSUE TITLE
Delay initialization of Stagemonitor plugins?

### ISSUE THREAD

**Issue by bloomper** [stagemonitor/stagemonitor#265]
Hi!

I am trying to integrate Stagemonitor with hybris (an e-commerce platform) with mixed success. I have implemented two plugins, one for JDBC and one for Ehcache. The stock JDBC plugin cannot be used as p6spy does not work with hybris as they cast here and there to their implementations. The stock Ehcache plugin cannot be used as hybris is using Ehcache 2.9.0.

Anyway, I have put Stagemonitor into a so called hybris extension which works fine for JDBC (but unfortunately only for database communication initiated from a web application and not for things initiated from the platform, e.g. scheduled jobs, as they lack a request trace). It does not work for Ehcache as an extension is loaded very early by the hybris bootstrap, so early that CacheManager,getCacheManager(null) returns null, i.e. Ehcache has not initialized. As hybris creates their caches programmatically, I need to register a CacheManagerEventListener but that is not possible since the CacheManager is null.

I then tried to put Stagemonitor as part of a web extension which is loaded much later and then the Ehcache plugin works fine. But then the JDBC plugin does not have any effect as a web extension is loaded within a class loader of its own which means that any classes loaded outside that class loader cannot be instrumented. This of course also affects the call tree, i.e. I only see classes and methods within the web extension, which makes it less useful.

After this long introduction, my question is whether it is possible to delay the initialization of a plugin or somehow trigger a re-initialization?

Thanks in advance!

Cheers,
Anders

**Comment by bloomper** [comment]
Hi again!

Do you have any ETA for 0.80? We are using Elastic 5.x so 0.80 is very much looked forward to... :)

Cheers,
Anders

**Comment by felixbarny** [comment]
You could try to exclude your ehcache plugin via configuration and then
manually init it later. It would be awesome if you could share the ehcache
plugin. I know there are many people waiting for support for newer ehcache
versions but as im busy with finishing 0.80.0 unfortunately, I don't have
the time for it. ETA is June.

Anders Jacobsson <notifications@github.com> schrieb am Mi., 31. Mai 2017
09:42:

**Comment by bloomper** [comment]
Hi!

Thanks for your prompt answer!

I will try out your proposal and I would be more than happy to share the Ehcache plugin but before I can do that, I need 0.80 to get the ES stuff working.

Cheers,
Anders

**Comment by felixbarny** [comment]
You can try out the latest snapshot available on the sonatype snapshot repository

**Comment by felixbarny** [comment]
I recently updated the ehcache plugin so that it initializes on the first incoming request: https://github.com/stagemonitor/stagemonitor/commit/31695c148e65b3aaf9ed4a80c921c3239f7d2a78
