### ISSUE TITLE
gradle maven central version 0.80.0.RC1 can not be found at this moment.

### ISSUE THREAD

**Issue by juneyoung** [stagemonitor/stagemonitor#266]
I followed this [guide](https://github.com/stagemonitor/stagemonitor/wiki/Step-1%3A-In-Browser-Widget)

I add dependencies into my `build.gradle` and got below messages

```
Could not find any version that matches org.stagemonitor:stagemonitor-web-servlet:[VERSION].
Versions that do not match:
    0.80.0.RC1
``` 
Maybe `stagemonitor-web-servlet` repo got some problem at this moment?

**Comment by felixbarny** [comment]
It should be available: http://search.maven.org/#artifactdetails%7Corg.stagemonitor%7Cstagemonitor-web-servlet%7C0.80.0.RC1%7Cjar

`compile 'org.stagemonitor:stagemonitor-web-servlet:0.80.0.RC1'`
So this does not work?

**Comment by juneyoung** [comment]
Thanks. it is working now. I did not update maven repository.
