### ISSUE TITLE
Webplugin from which package?

### ISSUE THREAD

**Issue by juneyoung** [stagemonitor/stagemonitor#267]
Hi. I am following the installation guide.
I got a question about in `new Webplugin().startup()` statement on the [Browser widget](https://github.com/stagemonitor/stagemonitor/wiki/Step-1%3A-In-Browser-Widget) step.

I could not find what package include this class. 
May I know what package to import to use this?

Thanks.

**Comment by felixbarny** [comment]
Whoops. Forgot to adjust the docs. Since 0.80.0.RC1 you don't have to add
this for spring boot 1.4+ applications.

Juneyoung <notifications@github.com> schrieb am Di., 13. Juni 2017 05:27:

**Comment by juneyoung** [comment]
Thanks for quick answer. bb
