### ISSUE TITLE
STAGEMONITOR_ACTIVE environment variable options is not working

### ISSUE THREAD

**Issue by unikulin** [stagemonitor/stagemonitor#270]
I'm try to enable/disable stagemonitor throughout environment variable.
STAGEMONITOR_ACTIVE=true or STAGEMONITOR_ACTIVE=TRUE is not working
I fond only one working options is enable by Java System Properties like this 
-Dstagemonitor.active=true this works fine, but any options to used environment variables?

**Comment by felixbarny** [comment]
How do you set the environment variable? The problem is that you usually can't change environment variables for a running process.

**Comment by unikulin** [comment]
I try a few options:
1. set env variable in IntelliJ and then run the application - no success
2. set env in docker env and then lunch container - same - no result.

**Comment by felixbarny** [comment]
Can you debug your application? If so, please try to execute `System.getenv("STAGEMONITOR_ACTIVE")`. What is the result? How do you set the docker env?

**Comment by felixbarny** [comment]
Also note that the order of the configuration sources is as follows:

- Transient Configuration Source
- Java System Properties
- stagemonitor.properties
- Environment Variables

So if you set `stagemonitor.active=false` in `stagemonitor.properties`, you can't override it via environment variables.

**Comment by felixbarny** [comment]
In the in browser widget you can see the order of the configuration sources, the current value of any configuration option and from which source this value was read from.

**Comment by unikulin** [comment]
This is a problem:
I define stagemonitor.active =false in stagemonitor.propertie.
Any option to disable stagemonitor by default and enable it by env variable?

**Comment by felixbarny** [comment]
You could remove it from stagemonitor.properties and only add an env variable `STAGEMONITOR_ACTIVE=false` if you want to disable stagemonitor.
