### ISSUE TITLE
How to use stagemonitor-jvm? There isn't any documentation on that

### ISSUE THREAD

**Issue by miptildar** [stagemonitor/stagemonitor#273]
I've already set up grafana with elasticsearch and launched stagemonitor-os (standalone) - everithing works fine, but my first priority is to collect infromation about JVM state and visualise it. 
P.S. I develop non servlet based app

**Comment by felixbarny** [comment]
Here is the documentation on how to integrate into non servlet applications: https://github.com/stagemonitor/stagemonitor/wiki/Integrate-stagemonitor-into-non-servlet-based-applications

If you are only interested in jvm metrics, use `stagemonitor-jvm` as the only dependency. If you want tracing, use `stagemonitor-tracing`.

**Comment by miptildar** [comment]
Thank you for reply!
Yes I've read this article, I've read almost all documentation :)
But there isn't any information in that article about connecting stagemonitor-jvm (more or less detailed).
I understand that _grafana_ waits for data from _elasticsearch_. And one must put required information into _elasticsearch_ and explain _grafana_ how that data should be visualised.
But how should I initialize this plugin? Will plugin initilization automatically create a new Dashboard at _grafana_?
Thanks.

**Comment by felixbarny** [comment]
The plugin initializes itself and automatically sends dashboards to grafana. Make sure that you have created a grafana api key and set it in stagemonitor.properties.

**Comment by miptildar** [comment]
Success.
Edited _stagemonitor.properties_ file using [configuration options](https://github.com/stagemonitor/stagemonitor/wiki/Configuration-Options#tracing-plugin), added maven dependencies. 
As you said, stagemonitor created dashboard itself, thanks!

**Comment by felixbarny** [comment]
nice :)
