### ISSUE TITLE
ES Credentials in logs

### ISSUE THREAD

**Issue by gopi-nath** [stagemonitor/stagemonitor#282]
Hi,

Since our ES cluster has the basic authentication, we are using url as suggested in documentation:  https://user:password@elasticsearch.dev.evivehealth.com

But the creds are coming in the logs as shown below.

13 Jul 2017 13:26:40,441  INFO  [qtp289180807-18] CorePlugin:506 - [] - [] - Sending metrics to Elasticsearch ([https://user:password@elasticsearch.dev.evivehealth.com]) every 1s

Is there any way to avoid this? We don't want others to see this credentials in logs.

**Comment by felixbarny** [comment]
You're right, that's too sensitive to log. I'll change it so that it will log `Sending metrics to Elasticsearch ([https://XXXX:XXXX@elasticsearch.dev.evivehealth.com]) every 1s`

**Comment by felixbarny** [comment]
will release today

**Comment by gopi-nath** [comment]
Make sure the same goes for all such logs.

**Comment by felixbarny** [comment]
I think it's not logged anywhere else. Btw its now released in 0.80.2

**Comment by gopi-nath** [comment]
Thanks. @felixbarny 
What about these logs?

10 Jul 2017 11:23:53,023  WARN  [async-elasticsearch] HttpClient:114 - [] - [] - Error sending POST request to url http://user:password@elasticsearch.dev.evivehealth.com/_bulk: Server returned HTTP response code: 503 for URL: http://user:password@elasticsearch.dev.evivehealth.com/_bulk


10 Jul 2017 11:23:53,023  WARN  [async-elasticsearch] HttpClient:115 - [] - [] - Error handling error response for POST request to url http://user:password@elasticsearch.dev.evivehealth.com/_bulk: Unexpected character ('<' (code 60)): expected a valid value (number, String, array, object, 'true', 'false' or 'null')


10 Jul 2017 11:41:04,766  WARN  [async-elasticsearch] HttpClient$ErrorLoggingResponseHandler:178 - [] - [] - http://user:password@elasticsearch.dev.evivehealth.com/_template/stagemonitor-metrics: 503 <!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">

**09 Jul 2017 14:32:40,473  INFO  [elasticsearch-tasks] ElasticsearchClient:238 - [] - [] - Deleting indices: Done http://user:password@elasticsearch.dev.evivehealth.com/stagemonitor-external-requests-*,-stagemonitor-external-requests-2017.07.09,-stagemonitor-external-requests-2017.07.08,-stagemonitor-external-requests-2017.07.07,-stagemonitor-external-requests-2017.07.06,-stagemonitor-external-requests-2017.07.05,-stagemonitor-external-requests-2017.07.04,-stagemonitor-external-requests-2017.07.03,-stagemonitor-external-requests-2017.07.02?timeout=20m&ignore_unavailable=true**

**Comment by felixbarny** [comment]
Fair point. Do you feel like creating a pull request for that?

**Comment by gggopi** [comment]
Sure.

**Comment by gggopi** [comment]
https://github.com/stagemonitor/stagemonitor/pull/284

**Comment by gggopi** [comment]
@felixbarny When will this be released?

**Comment by felixbarny** [comment]
I think I can release next week.

**Comment by felixbarny** [comment]
It's released: https://github.com/stagemonitor/stagemonitor/releases/tag/0.81.0
