### ISSUE TITLE
Prometheus collector exposing data in the wrong format

### ISSUE THREAD

**Issue by giannello** [stagemonitor/stagemonitor#298]
We want to switch from using Graphite to Prometheus for collecting our stagemonitor metrics.
The current implementation of the StagemonitorPrometheusCollector exposes metrics in a invalid format, and Prometheus is not willing to ingest them, failing with a `text format parsing error in line 4: second HELP line for metric name "jvm_memory_pools"` error.

The metrics endpoint, as exposed by Stagemonitor, contains the following
```
# HELP jvm_memory_pools Generated from stagemonitor metric import (metric=jvm_memory_pools, type=com.codahale.metrics.jvm.MemoryUsageGaugeSet$15)
# TYPE jvm_memory_pools gauge
jvm_memory_pools{memory_pool="PS-Survivor-Space",type="usage",} 0.6795399983723959
# HELP jvm_memory_pools Generated from stagemonitor metric import (metric=jvm_memory_pools, type=com.codahale.metrics.jvm.MemoryUsageGaugeSet$17)
# TYPE jvm_memory_pools gauge
jvm_memory_pools{memory_pool="PS-Survivor-Space",type="used",} 2137648.0
```

The `HELP` line should be unique per metric name.

**Comment by felixbarny** [comment]
Thx for reporting. The same problem seems to apply to `# TYPE` as well.
