### ISSUE TITLE
callTree message is wrong when  callTree message is wrong when the monitored method nests another monitored method

### ISSUE THREAD

**Issue by zhangxinming1991** [stagemonitor/stagemonitor#304]
callTree message is wrong when  callTree message is wrong when the monitored method nests another monitored method.For example, UpdateCustomer() is the monitored method, and GetCustomer() is also the  monitored method. if UpdateCustomer() invokes GetCustomer(), the CallTree message of UpdateCustomer is wrong, the problem is shown as follow:
![calltreeproblem](https://user-images.githubusercontent.com/17680370/29448776-d0e79dee-842a-11e7-9fb1-bbdd6032b4af.png)

**Comment by felixbarny** [comment]
> the CallTree message of UpdateCustomer is wrong

You mean that the timings are weird or that the `Method signature` is wrong?

**Comment by zhangxinming1991** [comment]
@felixbarny You mean that the timings are weird or that the Method signature is wrong?

Firstly, the timing is wrong because it is the start time rather than the used time. Secondly, the getCustomers() and HeavyOperation() is not included in the callTree message.
The code caused the problem is shown as follow:
    public Response updateCustomer(Customer customer) {//updateCustomer is the monitored method
        LOGGER.info("----invoking updateCustomer, Customer name is: " + customer.getName());
        if (customers.get(customer.getId()) == null) {
            return Response.notModified().build();
        }

        customers.put(customer.getId(), customer);

        getCustomers();//getCustomers is the monitored method

        ProblemSimple.HeavyOperation(1);
        return Response.ok().build();
    }

The right callTree message should be shown as follow:
![image](https://user-images.githubusercontent.com/17680370/29518564-76987b9a-86ac-11e7-9b9c-3bfc127b7d1b.png)

The reason of the problem is shown as follow:
![image](https://user-images.githubusercontent.com/17680370/29518844-a63d6b34-86ad-11e7-8347-dc6160d01815.png)

**Comment by zhangxinming1991** [comment]
@felixbarny You mean that the timings are weird or that the Method signature is wrong?

new root node is create when getCustomers()  is invoked, after it finished, the current pointer of callTree is null rather of updateCustomer(). So the methodCallParent.get() will return null.

**Comment by felixbarny** [comment]
Could you try if my solution works for you as well?

**Comment by felixbarny** [comment]
Did you already find the time to try this out?

**Comment by zhangxinming1991** [comment]
hi felix, I am sorry for my delayed reply.  I had tried your solution, but it still showed wrong message in the call Tree in the nested monitoring. The version i used to test is 0.80.2.
![problem](https://user-images.githubusercontent.com/17680370/29994978-54efc10c-9010-11e7-8b54-48c5672203ad.png)

**Comment by zhangxinming1991** [comment]
i use the way of Custom Instrumentation to monitor the updateCustomer method and i Implement class extending AbstractTracingTransformer, it showed wrong message of call Tree. However, if i use the way of Declaratively and use @Traced, it work well.

**Comment by zhangxinming1991** [comment]
i use the way of Custom Instrumentation to monitor the updateCustomer method and i Implement class extending AbstractTracingTransformer, it showed wrong message of call Tree. However, if i use the way of Declaratively and use @traced, it work well. The result is showed as follow:

![problem2](https://user-images.githubusercontent.com/17680370/29995296-cbb63e6c-9018-11e7-8f9a-70af26836e38.png)

But, in our project, way of Custom Instrumentation is more fit than way of Declaratively  to monitor the methods.

**Comment by felixbarny** [comment]
I should have noted that the fix is not released yet. So you will have to build a snapshot (`0.83.0-SNAPSHOT`) from source via `./gradlew install`.

**Comment by zhangxinming1991** [comment]
i use the way of Custom Instrumentation to monitor the updateCustomer method and i Implement class extending AbstractTracingTransformer, it showed wrong message of call Tree.Also,  i test the way of Declaratively and use @traced,  it also showed wrong message of call.
![image](https://user-images.githubusercontent.com/17680370/29995469-63f1cd2e-901c-11e7-819f-1a32df2bc1b3.png)

**Comment by zhangxinming1991** [comment]
ok, thank you

**Comment by zhangxinming1991** [comment]
Hi fexil, thanks for your solution, I tried with the fix and i found that it works and the call Tree don't break in the nested monitoring! But, i think it still has a flaw, for example, i could never get the call Tree of getCustomers() method which only be invoke in the updateCustomer(). If i want to analyse the call Tree of getCustomers(), i must set updateCustomer() as the filter in kibana, may be it is not very convenient.

**Comment by felixbarny** [comment]
But then you have duplicate information. You can use the "All Spans of This Trace" link to quickly navigate to updateCustomer().

You could also use the [stagemonitor kibana pugin](https://github.com/stagemonitor/stagemonitor-kibana). Note that at the moment it does not display the call tree, but we are currently working on it.
