### ISSUE TITLE
DNS issues if the X-Forwarded-For contains more than one IP

### ISSUE THREAD

**Issue by sconstro** [stagemonitor/stagemonitor#315]
Behaviour: if the request has a X-Forwarded-For with more than one IP (e.g. 10.1.1.1, 10.1.1.2) the stagemonitor will provoke a 8 seconds delay per request.

Problem:
inside org.stagemonitor.tracing.utils.SpanUtils.setClientIp(Span span, String clientIp) the issue is on the line
       InetAddress inetAddress = InetAddress.getByName(clientIp);
because clientIp is obtained inside MonitoredHttpRequest using String ip = request.getHeader("X-Forwarded-For");

Solution:  clientIp should be split based on comma and eventually take only one ip and use it inside InetAddress.getByName

**Comment by felixbarny** [comment]
Well, that's a bummer. Sorry for that.

Is it valid to have multiple IPs for `X-Forwarded-For`? Which should be picked?

**Comment by peter-thomas** [comment]
Yes, it is valid if there are multiple devices in the forwarding chain. The second to last value in the chain is typically the IP of the client request which was forwarded by the load balancer. 
So for example, if you have:
`x-forwarded-for = "addr0, addr1, addr2, addr3"`, then `addr2` is the one which should be used.

**Comment by sconstro** [comment]
The first one  is the IP of the browser and the last one is the  IP of the last proxy. I would take the first one but it will be great if you can make a flag to skip resolving because that can cause delays even with one IP. 

Thank you.

**Comment by felixbarny** [comment]
The first IP or the second to last one, which is it?

**Comment by peter-thomas** [comment]
As scontro stated, the first one is the actual IP address of the browser.

**Comment by felixbarny** [comment]
This should fix it: https://github.com/stagemonitor/stagemonitor/pull/316

I'll release a new version containing the fix not later than monday.

**Comment by felixbarny** [comment]
I did not forget about this but unfortunately could not find time today. Will release tomorrow.
