### ISSUE TITLE
StageMonitor APM  agent monitor TIBCO BW  

### ISSUE THREAD

**Issue by prashantnitt07** [stagemonitor/stagemonitor#333]
hi,
can be deploy StageMonitor  agent on TIBCO BW . please check and reply ,

We have four type to JAVA based ..
1. Tomcat
2. Weblogic
3. Jboss
4. TIBCO BW 
please reply all 4 java type supported StageMonitor .

**Comment by felixbarny** [comment]
Tomcat and JBoss are supported. Weblogic and TIBCO are not tested but stagemonitor should work with any Servlet 3+ servlet container.
