### ISSUE TITLE
Can't add subscriptions

### ISSUE THREAD

**Issue by arielsantana** [stagemonitor/stagemonitor#343]
When I click the **[+ Add]** button (Alerts --> Status), the screen hangs as if I were trying to open a popup.
Looking at the javascript console, I see that it tries to connect to:

http://localhost:8004/myApp/stagemonitor/incidents and
http://localhost:8004/myApp/stagemonitor/alerter-types,

**both request returns 404 not found.**

The rest of the plugins work well.

stagemonitor version: 0.85.0.RC1
stagemonitor dependencies: stagemonitor-web-servlet, stagemonitor-alerting, stagemonitor-logging, stagemonitor-os

![stagemonitor1](https://user-images.githubusercontent.com/4257780/32343107-46e6c4e2-bfe1-11e7-8a50-8583f04091a3.png)
![stagemonitor2](https://user-images.githubusercontent.com/4257780/32343111-4aedcb62-bfe1-11e7-84ab-22448412322b.png)

**Comment by felixbarny** [comment]
Seems like you are using spring boot. This issue is already fixed in master: https://github.com/stagemonitor/stagemonitor/commit/defc5138f441c555e4bb6bc8d04f752d37c64ad8

**Comment by arielsantana** [comment]
Hi Felix,
I download from master, build artifacts and test. And now I can add subscriptions perfectly.

Thanx!

**Comment by felixbarny** [comment]
:)
