### ISSUE TITLE
Support of Spring Cloud Config as a configuration source

### ISSUE THREAD

**Issue by felixoldenburg** [stagemonitor/stagemonitor#350]
Hi,

this is a feature request, but first let me explain our use case:
We're already using Stagemonitor in production and right now use Elasticsearch as a configuration source to configure tracing for our micro services.
From time to time we need to adapt the tracing factor for a specific service (means: for multiple instances for this service) e.g. to narrow down on a bug.
This is a little cumbersome as it involves creating a new ES configuration for this service and deploy a new version which has the new ES configuration source profile selected.
POSTing the configuration to all service instances every time is also not really an option.
It would be great to have a way to simply change the configuration for a service with hot reloading.

As we're also using a Spring Cloud Config server for all our configuration means (and having a specific set of services for every service already available), I propose to add Spring Cloud Config Server as a source of configuration as an alternative to ES (or file, env var, ... based configuration).

I already implemented a SpringCloudConfigConfigurationSource which involves a simple GET (with Stagemonitor's HttpClient) and has no dependencies to Spring at all.
After testing this a little more, I'll create a PR.

Any ideas or comments on this, so far?

Best,
Felix Oldenburg.

**Comment by felixbarny** [comment]
Nice, I was recently thinking about adding support for that. Afaiak Spring Cloud offers 3 formats: properties, yaml and json. Which one did you choose? The properties endpoint would have the advantage that it would likely work with other configuration storages as well.

**Comment by felixoldenburg** [comment]
Indeed I chose the {application}-{profile}.properties endpoint, as it seems to be the easiest one in terms of parsing. Also using the dash version (there's also a {application}/{profile}.* version) already provides an aggregated list of properties and one doesn't need to parse the Spring PropertySources.

I wasn't sure, though, if this is possible as a StagemonitorPlugin as it needs to be hooked into the config initialisation part. Mirroring the ElasticsearchConfigurationSource code did quite a good job I think. But I had to put it into the Stagemonitor core module(next to the ES one), because the HttpClient isn't available in the configuration module.

**Comment by felixbarny** [comment]
>  But I had to put it into the Stagemonitor core module(next to the ES one)

I'd put it in there as well 👍

**Comment by felixoldenburg** [comment]
PR [#352](https://github.com/stagemonitor/stagemonitor/pull/352)

**Comment by felixbarny** [comment]
Closed by #352
