### ISSUE TITLE
SSLConnectionSocketFactory NoClassDefFoundError

### ISSUE THREAD

**Issue by wuyezhong** [stagemonitor/stagemonitor#356]
I used **_org.apache.httpcomponents:httpclient_** in my project,and i got this Error while doing http request:

> NoClassDefFoundError | Could not initialize class org.apache.http.conn.ssl.SSLConnectionSocketFactory

I checked the dependency of **_stagemonitor-tracing-elasticsearch_**,and i found the same Classes with **_org.apache.http.xxxx**_ in this package _**com.uber.jaeger:jaeger-b3:0.22.0-RC1**_

Is there any way to solve this problem?

**Comment by felixbarny** [comment]
Could you try without stagemonitor-tracing-elasticsearch? Does it work then?

**Comment by wuyezhong** [comment]
Yeah, it worked without stagemonitor-tracing-elasticsearch,but i need it to export data to elasticsearch.
i tried to exculed jaeger-b3 and add it myself,like this : 

> 
        <dependency>
            <groupId>com.uber.jaeger</groupId>
            <artifactId>jaeger-b3</artifactId>
            <version>0.22.0-RC1</version>
            <exclusions>
                <exclusion>
                    <groupId>com.uber.jaeger</groupId>
                    <artifactId>jaeger-core</artifactId>
                </exclusion>
            </exclusions>
        </dependency>

it also worded.
but i don't know is there any problem with it.=_=

**Comment by felixbarny** [comment]
I'm sorry for the inconvenience, but unfortunately I can't update to Jaeger 0.22.0-RC2 because they have downgraded the opentracing API.

**Comment by danielfariati** [comment]
I also had to exclude the dependency because it was conflicting with apache httpclient.
