### ISSUE TITLE
stagemonitor for tomcat ROOT context

### ISSUE THREAD

**Issue by ragogitpub** [stagemonitor/stagemonitor#367]
Hello

For some reason i am able to start my tomcat server with stagemonitor and i can even load the stagemonitor with all the static files in the browser but for each of the requests to get the actual data i end up with a 404. In the access logs i see that the requests are being made for "/undefined/stagemonitor/metrics?metricName=something"

* tomcat 8.0.48 application server with all stagemonitor jar files and dependencies in tomcat_home/lib/ext
* the application jar file is in the tomcat ROOT context.

Is it possible to run stagemonitor in the ROOT context with the stagemonitor jar files and dependencies in the global classloader ?

Is there some magical property i can set to indicate that stagemonitor is running in the ROOT context ?

It almost seems like the initial part of the URL "/undefined" indicates that stagemonitor is always expecting stagemonitor to be running in some webapp( non ROOT context).

Thank you.

**Comment by felixbarny** [comment]
Did you find the problem with this? The root context should actually work.
