### ISSUE TITLE
ElasticSearchReporter could use the index's bulk endpoint instead of using the general one

### ISSUE THREAD

**Issue by yacota** [stagemonitor/stagemonitor#370]
In fact _ElasticSearchReporter_ could use the same approach as _ElasticsearchSpanReporter_ who does the following

    final String url = elasticsearchClient.getElasticsearchUrl() + "/" + getTodaysIndexName() + "/" + SPANS_TYPE + "/_bulk";

instead of accessing the general /_bulk endpoint directly

    httpClient.send("POST", corePlugin.getElasticsearchUrl() + "/_bulk", CONTENT_TYPE_JSON, metricsOutputStreamHandler, NoopResponseHandler.INSTANCE);

Thus we can protect the ES endpoint /_bulk , and just allow access to /stagemonitor-*/_bulk endpoint

**Comment by yacota** [comment]
@liebhaeuser maybe I am wrong but I think that SPANS_TYPE should be "metrics", not "spans"

**Comment by liebhaeuser** [comment]
@yacota no, your right. I fixed it. Thank you!
