### ISSUE TITLE
Distributed tracing not working

### ISSUE THREAD

**Issue by sumitsarkar** [stagemonitor/stagemonitor#377]
I have two Spring apps. One is the Spring Zuul gateway which proxies requests to an underlying service. Whenever, I trigger request to the underlying service, I can see two different `trace-id` showing up in Kibana. I included `stagemonitor-web-servlet` in both the services. 

Is there any other configuration that is required to allow same `traceId` to be used in the downstream service?

**Comment by sumitsarkar** [comment]
I think I need to write a filter to pass `traceId` to the downstream service. I am, however, not sure how to extract the `traceId` from the request. Is it even possible?

**Comment by trampi** [comment]
Hi, sorry for not replying earlier.
Have you fixed the problem?

**Comment by sumitsarkar** [comment]
Yes. I solved it. I found that the B3 headers were not being transmitted to the downstream system. I was using OkHttp as the underlying client in Zuul. So I wrote the instrumentation the same way, `stagemonitor-web-servlet` does for `SpringRestTemplate`. I included an OkHttp Interceptor anytime a constructor of OkHttp is called. It is a naive implementation where I didn't honor any of the stagemonitor configurations and basically marked all the requests with B3 sampled header to true.

This did solve the problem of getting two different `trace-id`. However, I should have instrumented the `ZuulServlet` as well. Now it results in two spans two be created. One that belongs to the Zuul gateway showing an external URL. And another of the downstream service (visually linked to the main trace instead of the external URL span). I didn't dig into how to solve this, but the current traces work fine for me. I'll do that after a couple of weeks.

And I apologize not posting what I did here. Did it in the Gitter room instead.

**Comment by BinWu1989** [comment]
@sumitsarkar ,Could you kindly give some advise?"stagemonitor-web-servlet does for SpringRestTemplate", do you mean the SpringRestTemplateContextPropagatingTransformer class? Seems it  doesn't work for me

**Comment by sumitsarkar** [comment]
@BinWu1989 I might not be remembering correctly (haven't used stagemonitor for over 6 months) but that seems right. `SpringRestTemplateContextPropagatingTransformer` injects the trace ids into the request. It will work for you only if you are using SpringRestTemplate. My question was related to Zuul 1.x. From what I remember, Zuul doesn't use SpringRestTemplate for forwarding requests.

**Comment by BinWu1989** [comment]
@sumitsarkar yes ,I am trying to inject the trace ids into the httpclient based requests

**Comment by BinWu1989** [comment]
@sumitsarkar what are you using now? I need a tool that don't need to install too much dependencies,just collect the data and then send it out the elasticsearch or orther storages, do you have any idea?

**Comment by sumitsarkar** [comment]
@BinWu1989 Well I was using Stagemonitor for over 6 months until my company chose to use NewRelic and got an Enterprise contract with them. So I moved to that. You could use DataDog too. I have heard good things about it. 

But in any case, the point of these dependencies are that you don't have to riddle your code with tracing code. That's why custom instrumentation like this exists. You might even need to write some custom instrumentation for any special use case you might have.
