### ISSUE TITLE
When add the dependency for stagemonitor-tracing-elasticsearch 0.88.0,there is an error for the jar jaeger-b3:0.22.0-RC1

### ISSUE THREAD

**Issue by rainishjj** [stagemonitor/stagemonitor#388]
When I add the dependency for stagemonitor-tracing-elasticsearch 0.88.0,there is an error for the jar jaeger-b3:0.22.0-RC1
![1](https://user-images.githubusercontent.com/28695335/36882075-bb1d81c8-1e0c-11e8-8ed2-65e8c9b070b6.png)
please give a solution,Thx!

**Comment by liebhaeuser** [comment]
Hi. Stagemonitor now depends on jaeger 0.24.0. Maybe you need to clean and rebuild your project.

Am 2. März 2018 04:28:05 MEZ schrieb rainishjj <notifications@github.com>:
>When I add the dependency for stagemonitor-tracing-elasticsearch
>0.88.0,there is an error for the jar jaeger-b3:0.22.0-RC1
>![1](https://user-images.githubusercontent.com/28695335/36882075-bb1d81c8-1e0c-11e8-8ed2-65e8c9b070b6.png)
>please give a solution,Thx!

-- 
iSYS Software GmbH

Andreas Liebhäuser, Dipl.-Inf. | Technischer Projektleiter

Tel: 089 462328-65 | Fax: 089 462328-14
Grillparzerstraße 10 | D-81675 München
N48°8'4" E11°36'42"
www.jstage.de / www.isys.de

Sitz der Gesellschaft: München | HRB 111760
Geschäftsführer: Prof. Dr. Peter Mandl und Michael Sailer

**Comment by liebhaeuser** [comment]
I just saw that there is the wrong dependency in the maven file. I'll fix that.
-- 
iSYS Software GmbH

Andreas Liebhäuser, Dipl.-Inf. | Technischer Projektleiter

Tel: 089 462328-65 | Fax: 089 462328-14
Grillparzerstraße 10 | D-81675 München
N48°8'4" E11°36'42"
www.jstage.de / www.isys.de

Sitz der Gesellschaft: München | HRB 111760
Geschäftsführer: Prof. Dr. Peter Mandl und Michael Sailer

**Comment by rainishjj** [comment]
ok, please give a reply after you fix it. Thanks very much!

**Comment by liebhaeuser** [comment]
I just released 0.88.1 which contains the correct commits. I'm sorry!!
