### ISSUE TITLE
Logo Proposal

### ISSUE THREAD

**Issue by loydjayme25** [stagemonitor/stagemonitor#411]
Can i submit my design for your project ? and also i can make a banner for Read Me.

**Comment by loydjayme25** [comment]
@liebhaeuser i am currently making it now sir, i send it as soon as i can finish it.

**Comment by liebhaeuser** [comment]
I don't know. You are not happy with the current one?

**Comment by ponschab** [comment]
Are you aware of the allusion of the project name to a [stage monitor system](https://en.wikipedia.org/wiki/Stage_monitor_system)?

**Comment by loydjayme25** [comment]
i am fine with the current one, since i am a student, i am proposing logo to enhance my skills in designing. i do hope you'll accept my design.

**Comment by loydjayme25** [comment]
my design if more likely an "eye" as a sense of monitoring.

**Comment by liebhaeuser** [comment]
Sorry, but we'll stick with the current one.
