### ISSUE TITLE
EUM error handling for Angular application

### ISSUE THREAD

**Issue by rtitlestad** [stagemonitor/stagemonitor#426]
Errors thrown in an Angular application don't seem to be captured by Weasel. I checked how Sentry/raven-js handles Angular applications and it seems they manually call a function to capture the error inside an Angular error handler: https://docs.sentry.io/clients/javascript/integrations/angular/

I want to do something similar with Weasel and I see that they have added a reportError command for this purpose: https://github.com/instana/weasel/commit/43fafd79e7bd8dce3bf72181edbd9414d8de8831

The current version of eum.js in stagemonitor is missing the reportError command though. Would it be possible to update Weasel to the latest version?

**Comment by liebhaeuser** [comment]
I have updated Weasel to the latest version. It will be part of the 0.88.5 release.
