### ISSUE TITLE
SpanWrappingTracer.activeSpan() does not follow behavior documented in Tracer interface

### ISSUE THREAD

**Issue by jpfourny** [stagemonitor/stagemonitor#428]
The method, _SpanWrappingTracer.activeSpan()_, is not following the behaviour defined in _io.opentracing.Tracer_ interface, specifically regarding handling the case where no active span is set in the current thread. 

According to the docs:

> @return the active {@link Span}. This is a shorthand for Tracer.scopeManager().active().span(),
     * and null will be returned if {@link Scope#active()} is null.

The _JaegerTracer_ implementation handles this correctly by returning a _null_ value. However, _SpanWrappingTracer_ raises a _NullPointerException_. An API consumer can easily work-around this by using _ScopeManager_, directly, but I would expect this convenience method to follow the standard.

**Comment by liebhaeuser** [comment]
You're right. The behaviour was changed and now SpanWrappingTracer.activeSpan() returns null if no active span is set.
