### ISSUE TITLE
without Spring boot only spring Integration

### ISSUE THREAD

**Issue by fthgul** [stagemonitor/stagemonitor#439]
Could you help me how can integrate stagemonitor with only spring (not spring boot) ?
My app generate a war and run in tomcat.

**Comment by liebhaeuser** [comment]
Hi,

The first thing is to make sure stagemonitor's ClassFileTransformer gets initialized.

Just call Stagemonitor.init() as early as possible in the lifecycle of your application. Ideally call it in the first line of your main method. The earlier stagemonitor is initialized the less files have to be retransformend, which is a expensive operation.

**Comment by fthgul** [comment]
Only adding dependencies in the pom.xml, stage monitor runs automatically.Of course you must set properties files, run kibana and elasticsearch before application.
