### ISSUE TITLE
ByteBuddy is outdated

### ISSUE THREAD

**Issue by svenruppert** [stagemonitor/stagemonitor#448]
Just not working on new JDKs or in combination with other libs using ByteBuddy

**Comment by cdalexndr** [comment]
Using Spring boot 2.1.6.RELEASE results in:

```
2019-07-25 16:28:38,826 ERROR [restartedMain] net.bytebuddy.agent.builder.AgentBuilder$Identified$Extendable.asDecorator()Lnet/bytebuddy/agent/builder/AgentBuilder;
java.lang.NoSuchMethodError: net.bytebuddy.agent.builder.AgentBuilder$Identified$Extendable.asDecorator()Lnet/bytebuddy/agent/builder/AgentBuilder;
	at org.stagemonitor.core.instrument.AgentAttacher.initByteBuddyClassFileTransformer(AgentAttacher.java:217)
	at org.stagemonitor.core.instrument.AgentAttacher.performRuntimeAttachment(AgentAttacher.java:85)
	at org.stagemonitor.core.Stagemonitor.reset(Stagemonitor.java:315)
	at org.stagemonitor.core.Stagemonitor.reset(Stagemonitor.java:297)
	at org.stagemonitor.core.Stagemonitor.init(Stagemonitor.java:58)
	at org.stagemonitor.web.servlet.ServletPlugin$Initializer.onStartup(ServletPlugin.java:503)
	at org.stagemonitor.web.servlet.initializer.ServletContainerInitializerUtil.registerStagemonitorServletContainerInitializers(ServletContainerInitializerUtil.java:24)
	at pse.Application$StagemonitorInitializer.onStartup(Application.java:159)
```
Stagemonitor uses 1.8.11, but hibernate(5.3.10.Final) requires bytebuddy 1.9.5.
This missing method was renamed to `asTerminalTransformation()` after 1.9.0 per [javadoc](https://bytebuddy.net/javadoc/1.9.0/net/bytebuddy/agent/builder/AgentBuilder.Identified.Extendable.html)

**Comment by liebhaeuser** [comment]
It should work if you add a dependency to byte buddy 1.8.x

Am 25. Juli 2019 15:42:26 MESZ schrieb cdalexndr <notifications@github.com>:
>Using Spring boot 2.1.6.RELEASE results in:
>
>```
>2019-07-25 16:28:38,826 ERROR [restartedMain]
>net.bytebuddy.agent.builder.AgentBuilder$Identified$Extendable.asDecorator()Lnet/bytebuddy/agent/builder/AgentBuilder;
>java.lang.NoSuchMethodError:
>net.bytebuddy.agent.builder.AgentBuilder$Identified$Extendable.asDecorator()Lnet/bytebuddy/agent/builder/AgentBuilder;
>	at
>org.stagemonitor.core.instrument.AgentAttacher.initByteBuddyClassFileTransformer(AgentAttacher.java:217)
>	at
>org.stagemonitor.core.instrument.AgentAttacher.performRuntimeAttachment(AgentAttacher.java:85)
>	at org.stagemonitor.core.Stagemonitor.reset(Stagemonitor.java:315)
>	at org.stagemonitor.core.Stagemonitor.reset(Stagemonitor.java:297)
>	at org.stagemonitor.core.Stagemonitor.init(Stagemonitor.java:58)
>	at
>org.stagemonitor.web.servlet.ServletPlugin$Initializer.onStartup(ServletPlugin.java:503)
>	at
>org.stagemonitor.web.servlet.initializer.ServletContainerInitializerUtil.registerStagemonitorServletContainerInitializers(ServletContainerInitializerUtil.java:24)
>	at
>pse.Application$StagemonitorInitializer.onStartup(Application.java:159)
>```
>Stagemonitor uses 1.8.11, but hibernate(5.3.10.Final) requires
>bytebuddy 1.9.5.
>This missing method was renamed to `asTerminalTransformation()` after
>1.9.0 per
>[javadoc](https://bytebuddy.net/javadoc/1.9.0/net/bytebuddy/agent/builder/AgentBuilder.Identified.Extendable.html)
>
>-- 
>You are receiving this because you were assigned.
>Reply to this email directly or view it on GitHub:
>https://github.com/stagemonitor/stagemonitor/issues/448#issuecomment-515048418

-- 
iSYS Software GmbH

Andreas Liebhäuser, Dipl.-Inf. | Technischer Projektleiter

Tel: 089 462328-65 | Fax: 089 462328-14
Grillparzerstraße 10 | D-81675 München
N48°8'4" E11°36'42"
www.jstage.de / www.isys.de

Sitz der Gesellschaft: München | HRB 111760
Geschäftsführer: Prof. Dr. Peter Mandl und Michael

**Comment by cdalexndr** [comment]
Indeed, added the dependency to gradle to froce version and it works:
`implementation 'net.bytebuddy:byte-buddy:1.8.11'`
