### ISSUE TITLE
Missing es/5/stagemonitor-elasticsearch-span-index-template

### ISSUE THREAD

**Issue by thaarbach** [stagemonitor/stagemonitor#476]
If using ES 5 reporting to ES fails because of missing es index templates for es 5

https://github.com/stagemonitor/stagemonitor/blob/20317e9e530a9e91b22a875ebef922543eaf14e1/stagemonitor-core/src/main/java/org/stagemonitor/core/elasticsearch/ElasticsearchClient.java#L91-L98

**Comment by daiqizhong** [comment]
Whether 0.89.1 supports ES7.6.2 and grafana 6.7.2

**Comment by thaarbach** [comment]
@dimon-v
haven't tested it yet. PullRequests are welcome.
