### ISSUE TITLE
Whether 0.89.1 supports ES7.6.2 and grafana 6.7.2

### ISSUE THREAD

**Issue by dimon-v** [stagemonitor/stagemonitor#478]
Hi
I`m use elasticseach 7.6.2 and grafana 6.7.2。
open grafana host dashboard
Templating init failed，Cannot read property 'text' of undefined

**Comment by thaarbach** [comment]
@dimon-v https://github.com/stagemonitor/stagemonitor/issues/476#issuecomment-625166044

**Comment by dimon-v** [comment]
OK，Thanks
