### ISSUE TITLE
info define aspect message upon startup

### ISSUE THREAD

**Issue by larue3000** [stagemonitor/stagemonitor#51]
While attempting to use the ProfilerAspect, the message "info define aspect" is being written to log.  I based my aop.xml configuration at the PetClinic demo aop.xml.  The PetClinic demo exhibited the same message.

[AppClassLoader@126f304] info AspectJ Weaver Version 1.8.2 built on Thursday Aug 14, 2014 at 21:45:02 GMT
[AppClassLoader@126f304] info register classloader sun.misc.Launcher$AppClassLoader@126f304
[AppClassLoader@126f304] info using configuration /C:/Development/Tools/jersey-archive-1.5/META-INF%5cmyaop.xml
[AppClassLoader@126f304] info register aspect org.stagemonitor.core.metrics.aspects.TimedAspect
[AppClassLoader@126f304] info register aspect org.stagemonitor.core.metrics.aspects.MeteredAspect
[AppClassLoader@126f304] info register aspect org.stagemonitor.jdbc.ConnectionMonitorAspect
[AppClassLoader@126f304] info register aspect org.stagemonitor.logging.InformationAppendingLoggingAspect
[AppClassLoader@126f304] info register aspect org.stagemonitor.logging.MeterLoggingAspect
[AppClassLoader@126f304] info define aspect profiler

<!DOCTYPE aspectj PUBLIC
        "-//AspectJ//DTD//EN" "http://www.eclipse.org/aspectj/dtd/aspectj.dtd">
<aspectj>
    <weaver options="-Xlint:ignore -verbose -showWeaveInfo">
		<exclude within="com.sun.proxy..*" />
    </weaver>

    <aspects>
        <concrete-aspect name="profiler" extends="org.stagemonitor.requestmonitor.profiler.ProfilingAspect">
            <pointcut name="methodsToProfile" expression="execution(* ses..*(..))"/>
        </concrete-aspect>
        
        <aspect name="org.stagemonitor.core.metrics.aspects.TimedAspect"/>
        <aspect name="org.stagemonitor.core.metrics.aspects.MeteredAspect"/>
        <aspect name="org.stagemonitor.jdbc.ConnectionMonitorAspect"/>
        <aspect name="org.stagemonitor.logging.InformationAppendingLoggingAspect"/>
        <aspect name="org.stagemonitor.logging.MeterLoggingAspect"/>
    </aspects>
</aspectj>

Any assistance in resolving the problem or misunderstanding would be appreciated.

**Comment by felixbarny** [comment]
I'm closing this issue because you didn't respond in over 30 days. Feel free to reopen if you need more help.
