### ISSUE TITLE
Contributing additional RequestTraceReporter implementations

### ISSUE THREAD

**Issue by shiftyeyes** [stagemonitor/stagemonitor#54]
I have a need to have a RequestTraceReporter that will report traces to [Splunk](http://www.splunk.com). Currently there is not a way to contribute additional implementations of the RequestTraceReporter without changing stagemonitor itself. One way to contribute additional RequestTraceReporter implementations would be to use the ServiceLoader to look up additional implementations [1]. What are your thoughts on this approach? 

Thanks for the great project!

[1]
From org.stagemonitor.requestmonitor.RequestMonitor
````java
private static final List<RequestTraceReporter> requestTraceReporters = new CopyOnWriteArrayList<RequestTraceReporter>(){{
	add(new LogRequestTraceReporter());
	add(new ElasticsearchRequestTraceReporter());
	for (RequestTraceReporter requestTraceReporter : ServiceLoader.load(RequestTraceReporter.class)) {
		add(requestTraceReporter);
	}
}};
````

**Comment by felixbarny** [comment]
You can add `RequestTraceReporter`s at runtime with `RequestMonitor.addRequestTraceReporter(RequestTraceReporter requestTraceReporter)`

**Comment by shiftyeyes** [comment]
I missed that method. Thanks for pointing me in the right direction.

**Comment by felixbarny** [comment]
np, glad I could help. What does Splunk offer that the stagemonitor Kibana dashboard does not?

**Comment by shiftyeyes** [comment]
We use Splunk for your REST service log monitoring and tracing. We currently have dashboards for our services in Splunk, so the desire was to add additional graphs from the data provided by the request trace reporter. We also didn't want to add an additional system to our architecture if possible. The functionality provided by both Splunk and Kibana are very similar.
