### ISSUE TITLE
Small typo

### ISSUE THREAD

**Issue by jhiemer** [stagemonitor/stagemonitor#57]
Hi,
I am not sure, what I saw is that the Boomerang Injector potentially needs to be renamed: 

https://github.com/stagemonitor/stagemonitor/blob/584f8fe0b99ec09e3a5f988d01c1f0680b52c3b1/stagemonitor-web/src/main/java/org/stagemonitor/web/monitor/rum/BommerangJsHtmlInjector.java

to BoomerangJsHtmlInjector.java?

**Comment by felixbarny** [comment]
Thx for spotting that
