### ISSUE TITLE
Datastore for metrics

### ISSUE THREAD

**Issue by jhiemer** [stagemonitor/stagemonitor#58]
Hi,
me again, having questions. The background of my questions is, that I don't want to use Grafana, but instead a combination of AngularJS and Highcharts with InfluxDB in the backend. 

The question are:
Which time series database are you using in the backend in your Docker image?
How do you fill the database?

(Could not find both, perhaps I did not look properly). :-(

What I am currently building is something similar to the query and charting definition in grafana, but with different technologies and a pure Java/Angular/Bootstrap stack.

**Comment by jhiemer** [comment]
Ok, I found something for storing in Influx, which would integrate very nice: https://github.com/davidB/metrics-influxdb

**Comment by felixbarny** [comment]
Hi,
why don't you want to use grafana? It is also built with AngularJS. You could use it as a foundation of your implementation (and maybe contribute your changes). Just a thought.

As InfluxDB understands the the graphite protocol natively http://influxdb.com/docs/v0.8/api/reading_and_writing_data.html#writing-data-through-graphite-protocol, it should be possible to point stagemonitor to InfluxDB's graphite endpoint. That would probably be the easiest way.

**Comment by jhiemer** [comment]
Hi,
it is some kind of educational project for me, and I am trying to understand/use some concepts and implement them with AJS and Spring. 

Thanks for your response!
