### ISSUE TITLE
Wish stagemonitor.property.overrides allows external filesystem property file

### ISSUE THREAD

**Issue by zucher** [stagemonitor/stagemonitor#62]
Hello,

Currently the PropertyFileConfigurationSource file is restrict to callpath location for stagemonitor.properties file.

Could you support as failover of getResourceAsStream() request an alternative file open on filesystem.

Regards

zucher

**Comment by felixbarny** [comment]
Sure, that's a good suggestion.

**Comment by zucher** [comment]
Thank you :+1:
