### ISSUE TITLE
Where are stagemonitor internal metrics stored?

### ISSUE THREAD

**Issue by yacota** [stagemonitor/stagemonitor#63]
As described in docs, https://github.com/stagemonitor/stagemonitor/wiki/Configuration-Options#internal-monitoring  , we have configured stagemonitor to collect internal performance data. 
But where I can see this data? Neither in grafana nor in kibana I was able to see anything

Thanks

**Comment by felixbarny** [comment]
I haven't yet configured a dashboard for that but those metrics are written to the log just like the other ones. Search for metrics containing `internal`. You can also create graphs in grafana if you want.

**Comment by yacota** [comment]
Can I create an issue in order to keep an eye on it ? 
Thanks

**Comment by felixbarny** [comment]
Do you mean a feature request for a grafana dashboard?

**Comment by yacota** [comment]
Exactly

**Comment by felixbarny** [comment]
Sure you can. But at the moment I'm quite busy finishing the alerting component and preparing for conferences. So it woud be awesome if you could do a pull request for that. Creating a dashboard in grafana is really easy. Once you're done, export it as JSON and send it to elasticsearch like that: https://github.com/stagemonitor/stagemonitor/blob/595fb00255a8c47e8b2ad85246cacc9d2a60739b/stagemonitor-core/src/main/java/org/stagemonitor/core/CorePlugin.java#L202

**Comment by yacota** [comment]
i will definitely take a look at it

Thanks again

**Comment by felixbarny** [comment]
:+1: 
I'm closing this issue. Feel free to create another one for the feature request.
