### ISSUE TITLE
Uplift Metrics version to 3.1.1 for improved Graphite connectivity

### ISSUE THREAD

**Issue by alecxvs** [stagemonitor/stagemonitor#67]
Related to https://github.com/dropwizard/metrics/issues/694
3.1.1 of Metrics corrects a problem with losing connectivity to Graphite and being unable to reconnect until the application is restarted.

**Comment by felixbarny** [comment]
I already had it in my local master ;)
https://github.com/stagemonitor/stagemonitor/commit/54ad5842416dbe2caca31a87ded9136f1db6a5ac
