### ISSUE TITLE
Allow deployment in servlet-api-2.5 containers

### ISSUE THREAD

**Issue by barclay-reg** [stagemonitor/stagemonitor#72]
currently, running stagemonitor in older environments (which only support serlet-api-2.5) is not possible.

making it easier to integrate stagemonitor also to this systems would be great (see aslo https://github.com/stagemonitor/stagemonitor-mailinglist/issues/5)

**Comment by felixbarny** [comment]
Which application server are you using?

**Comment by barclay-reg** [comment]
sorry, I don't know good example applications
 
I'm using weblogic 10.3.6
but tomcat 6.x is also a 2.5 server, maybe you find some examples there (or the tomcat manager webapp is 2.5 based)

**Comment by felixbarny** [comment]
To be honest to you, servlet 2.5 and especially WebLogic is not a priority right now. But feel free to contact me via email if you are interested in funding the development.
