### ISSUE TITLE
Injecting the stagemonitor HTML does not recalculate the Content-Length HTTP Header

### ISSUE THREAD

**Issue by trampi** [stagemonitor/stagemonitor#74]
Initial problem described here:
https://github.com/stagemonitor/stagemonitor-mailinglist/issues/6

The following lines need to raise the content length header (if it was originally set):
https://github.com/stagemonitor/stagemonitor/blob/master/stagemonitor-web/src/main/java/org/stagemonitor/web/monitor/filter/HttpRequestMonitorFilter.java#L175

**Comment by felixbarny** [comment]
I think it should be sufficient to omit the content-lengh header in case the widget was injected.

**Comment by felixbarny** [comment]
Did 0.15.2 fix your issue?

**Comment by johanstenberg92** [comment]
@felixbarny I'm guessing I have this problem too, since some of my static pages does not display correctly.

**Comment by felixbarny** [comment]
What is wrong with you static pages?
