### ISSUE TITLE
HttpClient Has Massive Leaks

### ISSUE THREAD

**Issue by swillson** [stagemonitor/stagemonitor#78]
We recently changed one of our java services that uses StageMonitor to get a significantly larger amount of load. As a result we had all kinds of crashes that we dug into and found 10's of 100's of thousands of connections in CLOSE_WAIT state after pushing execution stacks into elastic search.

Digging into the code, to me, it looks like this class:

`stagemonitor/stagemonitor-core/src/main/java/org/stagemonitor/core/util/HttpClient.java`

No where in the code, or any of the calling code, to the send* methods is the URL connection that is returned being closed. 

We tried adjusting the machines reaping (Ubuntu machine, 1.7 JVM, 64GB memory) to reap the connections more often but these never cleaned up and again the process killed the JVM due to too many open file handles.

For now the workaround was:

`-Dstagemonitor.elasticsearch.configurationSource.deactivateStagemonitorIfEsIsDown=false -Dstagemonitor.elasticsearch.url=`

To just shut off the call stack recording.

Has anyone else reported this issue? I'm not sure what kind of load this has been tested in or different OS configurations but maybe it isn't a feature we should enable anyhow under load.

**Comment by felixbarny** [comment]
You are right, the InputStream of the URL connection has to be closed in order that the underlying TCP connection can be reused for another HTTP connection.

**Comment by felixbarny** [comment]
I have just released 0.15.1 with this fix
