### ISSUE TITLE
Add ResteasyRequestNameDeterminerInstrumenter

### ISSUE THREAD

**Issue by johnlcox** [stagemonitor/stagemonitor#80]
There is already a request name determiner for Spring MVC projects. We are using Resteasy for our projects and will be implementing a similar mechanism for Resteasy requests. Before I implement it I wanted to see if there was a preference on how it names things.

We would prefer if it did something like `ResourceClass#requestMethod` which is different from what the Spring MVC request names are. Would this difference be OK?

**Comment by felixbarny** [comment]
Maybe a good way would be to have a configurable naming strategy or something. That way you could configure how to name things in one place.
For example, NamingStrategy.METHOD would behave like the default and NamingStrategy.CLASS_METHOD would be like your suggestion.

**Comment by felixbarny** [comment]
I've implemented some naming strategies: https://github.com/stagemonitor/stagemonitor/blob/master/stagemonitor-requestmonitor/src/main/java/org/stagemonitor/requestmonitor/BusinessTransactionNamingStrategy.java

**Comment by johnlcox** [comment]
Fixed with #82
