### ISSUE TITLE
Broken with start tomcat 7 with Oracle Jdk7

### ISSUE THREAD

**Issue by fdefigueiredo-technisys** [stagemonitor/stagemonitor#84]
Hi, i have a problem with implementation stagemonitor in my application. I added dependency and application compile OK. But application it is starting get error org.stagemonitor.javassist ( https://gist.github.com/fdefigueiredo-technisys/beedde73c1c18d55cf05 ).
This error is repeated several times with different classes of WS (Cxf). When application finish i try test run app (send request) but when try connect to DB (using c3p0) get exception. 

https://gist.github.com/fdefigueiredo-technisys/ad68e31b0f74c3c3adf5

Thanks alot for your help. 
Diego

**Comment by felixbarny** [comment]
I'm sorry for the difficulties you have with stagemonitor. Could you provide a example application that I can use to reproduce the problem?

**Comment by felixbarny** [comment]
Feel free to reopen if the fix does not work
