### ISSUE TITLE
Which .jar files need to include in non maven spring project

### ISSUE THREAD

**Issue by narender-balauda** [stagemonitor/stagemonitor#85]
Hi, i have a problem with implementation stagemonitor in my spring application(non maven). I added `stagemonitor-web-0.15.2.jar`. But when i compiling the project then it gives me this error:
`java.lang.NoClassDefFoundError: org.stagemonitor.core.StagemonitorPlugin`

After that i thought may be it needs `stagemonitor-core-0.15.2.jar`. So, i added it also. Then it started giving another error:
`java.lang.NoClassDefFoundError: com.codahale.metrics.SharedMetricRegistries`

So, i added `metrics-core-3.0.2.jar` also. But no luck !!!
It keep asking me more jars.

Please Help.

**Comment by felixbarny** [comment]
There is a chapter about that in the installation guide: https://github.com/stagemonitor/stagemonitor/wiki/Step-1%3A-Prerequisites#no-dependency-management

But this is something I'm currently working on to simplify

**Comment by narender-balauda** [comment]
Hi Felix,

Thanks a lot of your quick response.

You instructed that we need to include all libs in the project:
* stagemonitor-web-[version].jar is in stagemonitor-web/build/libs/lib
* all transitive dependencies for stagemonitor-web are in stagemonitor-web/build/libs/lib

I followed your instructions but i could not even find `stagemonitor-web/build/libs/lib` folder. 
So, i included '`stagemonitor-web-0.15.2.jar` by downloading it from [mvnrepository](http://mvnrepository.com/artifact/org.stagemonitor/stagemonitor-web/0.15.2) but i don't know which are the **all transitive dependencies for stagemonitor-web**.

So, if you could name me the **all transitive dependencies for stagemonitor-web**, i will download and use into my project.

Thanks a lot,
Naren

**Comment by felixbarny** [comment]
Are you sure you have executed `./gradlew copyToLib`? I've just double checked and the `stagemonitor-web/build/libs/lib` folder does exist.

**Comment by narender-balauda** [comment]
Hi Felix,

I have windows and i ran the command `gradlew.bat copyToLib`. Where `copyToLib` was a folder name in same directory and it started downloading the gradle and created a `.gradle` folder. But nothing happened into `stagemonitor-web` folder. My `stagemonitor-web` folder have only `src` folder and `build.gradle` file.


Thanks for the help.

**Comment by felixbarny** [comment]
What do you mean by "copyToLib was a folder name in same directory"? Is there a folder named copyToLib in the stagemonitor folder?? Actually copyToLib is a target for the gradle build that compiles the project and collects all transitive dependencies.

Please try again to cd into the stagemonitor folder, then execute gradlew.bat copyToLib. After that go to stagemonitor\stagemonitor-web\build\libs\lib with the explorer.

**Comment by narender-balauda** [comment]
Hi Felix,

Actually the problem is that the `git.bash` was ignoring that command so i created a folder myself (thought its not a part of command). 
I got `stagemonitor\stagemonitor-web\build\libs\lib` now with following 40 .jars.

![image](https://cloud.githubusercontent.com/assets/11943748/8507318/8f41f00c-225b-11e5-9167-85e01feadc35.png)


Thanks a lot for the immediate and great HELP.
Naren

**Comment by felixbarny** [comment]
Hm, wait a moment. There are way more than needed. There is some more work for me to do to make this work again :/

**Comment by narender-balauda** [comment]
Hi Felix,

I did all the configurations:
1. Added all jar libraries
2. I have self4j configured in my project
3. I am using servlet-api 3.0 and `web.xml`
4. My `web.xml` contains the `<display-name>`
5. Stagemonitor configuration file exists in classpath.

My project compiled OK. But i can't see the speaker icon(Stagemonitor icon) on bottom right of the page.

**Note: I am using ftl pages for view.**

Thanks in advance.

**Comment by felixbarny** [comment]
This project helps you to get all the dependencies:

https://github.com/felixbarny/stagemonitor-get-all-libs

**Comment by narender-balauda** [comment]
Hi Felix,

Thanks, but still not getting the speaker icon(Stagemonitor Browser Widget icon) on bottom right of the freemarker view when project runs.
Any clue ?

**Comment by felixbarny** [comment]
Anything in the logs?

**Comment by felixbarny** [comment]
Also make sure to remove all jars you got from stagemonitor\stagemonitor-web\build\libs\lib and stagemonitor\stagemonitor-web\build\libs

**Comment by narender-balauda** [comment]
Hi felix,

No Errors in tomcat logs.
Yes i am only using jars from `stagemonitor-get-all-libs-master\build`.

**Comment by felixbarny** [comment]
Could you paste the logs of the startup here?

**Comment by narender-balauda** [comment]
Here are the logs:

`"E:\Intellij_IDEA\Tomcat Servers\myOrderica-7.0.56\bin\catalina.bat" run
[2015-07-04 05:07:14,835] Artifact trunk:war exploded: Server is not connected. Deploy is not available.
Using CATALINA_BASE:   "C:\Users\ABC\.IntelliJIdea14\system\tomcat\Unnamed_trunk"
Using CATALINA_HOME:   "E:\Intellij_IDEA\Tomcat Servers\tomcat-7.0.56"
Using CATALINA_TMPDIR: "E:\Intellij_IDEA\Tomcat Servers\tomcat-7.0.56\temp"
Using JRE_HOME:        "C:\Program Files\Java\jdk1.7.0_67"
Using CLASSPATH:       "E:\Intellij_IDEA\Tomcat Servers\tomcat-7.0.56\bin\bootstrap.jar;E:\Intellij_IDEA\Tomcat Servers\tomcat-7.0.56\bin\tomcat-juli.jar"
Connected to the target VM, address: '127.0.0.1:55120', transport: 'socket'
Jul 04, 2015 5:07:17 PM org.apache.catalina.core.AprLifecycleListener init
INFO: Loaded APR based Apache Tomcat Native library 1.1.31 using APR version 1.4.8.
Jul 04, 2015 5:07:17 PM org.apache.catalina.core.AprLifecycleListener init
INFO: APR capabilities: IPv6 [true], sendfile [true], accept filters [false], random [true].
Jul 04, 2015 5:07:18 PM org.apache.catalina.core.AprLifecycleListener initializeSSL
INFO: OpenSSL successfully initialized (OpenSSL 1.0.1h 5 Jun 2014)
Jul 04, 2015 5:07:19 PM org.apache.coyote.AbstractProtocol init
INFO: Initializing ProtocolHandler ["http-apr-8080"]
Jul 04, 2015 5:07:19 PM org.apache.coyote.AbstractProtocol init
INFO: Initializing ProtocolHandler ["ajp-apr-8009"]
Jul 04, 2015 5:07:19 PM org.apache.catalina.startup.Catalina load
INFO: Initialization processed in 3370 ms
Jul 04, 2015 5:07:19 PM org.apache.catalina.core.StandardService startInternal
INFO: Starting service Catalina
Jul 04, 2015 5:07:19 PM org.apache.catalina.core.StandardEngine startInternal
INFO: Starting Servlet Engine: Apache Tomcat/7.0.56
Jul 04, 2015 5:07:19 PM org.apache.coyote.AbstractProtocol start
INFO: Starting ProtocolHandler ["http-apr-8080"]
Jul 04, 2015 5:07:19 PM org.apache.coyote.AbstractProtocol start
INFO: Starting ProtocolHandler ["ajp-apr-8009"]
Jul 04, 2015 5:07:19 PM org.apache.catalina.startup.Catalina start
INFO: Server startup in 306 ms
[2015-07-04 05:07:19,732] Artifact trunk:war exploded: Artifact is being deployed, please wait...
Connected to server
Jul 04, 2015 5:07:29 PM org.apache.catalina.startup.HostConfig deployDirectory
INFO: Deploying web application directory E:\Intellij_IDEA\Tomcat Servers\myOrderica-7.0.56\webapps\manager
Jul 04, 2015 5:07:30 PM org.apache.catalina.startup.HostConfig deployDirectory
INFO: Deployment of web application directory E:\Intellij_IDEA\Tomcat Servers\myOrderica-7.0.56\webapps\manager has finished in 1,024 ms
Jul 04, 2015 5:07:43 PM org.apache.catalina.startup.TaglibUriRule body
INFO: TLD skipped. URI: http://jakarta.apache.org/struts/tags-tiles is already defined
Jul 04, 2015 5:07:43 PM org.apache.catalina.startup.TaglibUriRule body
INFO: TLD skipped. URI: http://www.springframework.org/tags is already defined
Jul 04, 2015 5:07:43 PM org.apache.catalina.startup.TaglibUriRule body
INFO: TLD skipped. URI: http://java.sun.com/jsp/jstl/core is already defined
Jul 04, 2015 5:07:43 PM org.apache.catalina.startup.TaglibUriRule body
INFO: TLD skipped. URI: http://java.sun.com/jstl/core_rt is already defined
Jul 04, 2015 5:07:43 PM org.apache.catalina.startup.TaglibUriRule body
INFO: TLD skipped. URI: http://java.sun.com/jstl/core is already defined
Jul 04, 2015 5:07:43 PM org.apache.catalina.startup.TaglibUriRule body
INFO: TLD skipped. URI: http://java.sun.com/jstl/fmt_rt is already defined
Jul 04, 2015 5:07:43 PM org.apache.catalina.startup.TaglibUriRule body
INFO: TLD skipped. URI: http://java.sun.com/jstl/fmt is already defined
Jul 04, 2015 5:07:43 PM org.apache.catalina.startup.TaglibUriRule body
INFO: TLD skipped. URI: http://jakarta.apache.org/taglibs/standard/permittedTaglibs is already defined
Jul 04, 2015 5:07:43 PM org.apache.catalina.startup.TaglibUriRule body
INFO: TLD skipped. URI: http://jakarta.apache.org/taglibs/standard/scriptfree is already defined
Jul 04, 2015 5:07:43 PM org.apache.catalina.startup.TaglibUriRule body
INFO: TLD skipped. URI: http://java.sun.com/jstl/sql_rt is already defined
Jul 04, 2015 5:07:43 PM org.apache.catalina.startup.TaglibUriRule body
INFO: TLD skipped. URI: http://java.sun.com/jstl/sql is already defined
Jul 04, 2015 5:07:43 PM org.apache.catalina.startup.TaglibUriRule body
INFO: TLD skipped. URI: http://java.sun.com/jstl/xml_rt is already defined
Jul 04, 2015 5:07:43 PM org.apache.catalina.startup.TaglibUriRule body
INFO: TLD skipped. URI: http://java.sun.com/jstl/xml is already defined
Jul 04, 2015 5:07:43 PM org.apache.catalina.startup.TaglibUriRule body
INFO: TLD skipped. URI: http://ckeditor.com is already defined
17:07:43,490 |-INFO in ch.qos.logback.classic.LoggerContext[default] - Could NOT find resource [logback.groovy]
17:07:43,491 |-INFO in ch.qos.logback.classic.LoggerContext[default] - Could NOT find resource [logback-test.xml]
17:07:43,491 |-INFO in ch.qos.logback.classic.LoggerContext[default] - Found resource [logback.xml] at [file:/E:/Intellij_IDEA/tomcat-03-2015/trunk/out/artifacts/trunk_war_exploded/WEB-INF/classes/logback.xml]
17:07:43,722 |-INFO in ch.qos.logback.classic.joran.action.ConfigurationAction - debug attribute not set
17:07:43,723 |-INFO in ch.qos.logback.core.joran.action.AppenderAction - About to instantiate appender of type [ch.qos.logback.core.ConsoleAppender]
17:07:43,728 |-INFO in ch.qos.logback.core.joran.action.AppenderAction - Naming appender as [STDOUT]
17:07:43,796 |-WARN in ch.qos.logback.core.ConsoleAppender[STDOUT] - This appender no longer admits a layout as a sub-component, set an encoder instead.
17:07:43,796 |-WARN in ch.qos.logback.core.ConsoleAppender[STDOUT] - To ensure compatibility, wrapping your layout in LayoutWrappingEncoder.
17:07:43,796 |-WARN in ch.qos.logback.core.ConsoleAppender[STDOUT] - See also http://logback.qos.ch/codes.html#layoutInsteadOfEncoder for details
17:07:43,797 |-INFO in ch.qos.logback.core.joran.action.AppenderAction - About to instantiate appender of type [ch.qos.logback.core.rolling.RollingFileAppender]
17:07:43,800 |-INFO in ch.qos.logback.core.joran.action.AppenderAction - Naming appender as [FILE]
17:07:43,831 |-INFO in c.q.l.core.rolling.TimeBasedRollingPolicy - No compression will be used
17:07:43,833 |-INFO in c.q.l.core.rolling.TimeBasedRollingPolicy - Will use the pattern E:/Intellij_IDEA/Tomcat Servers/myOrderica-7.0.56/logs/myorderica.%d{yyyy-MM-dd}.%i.log for the active file
17:07:43,836 |-INFO in ch.qos.logback.core.rolling.SizeAndTimeBasedFNATP@12e07f77 - The date pattern is 'yyyy-MM-dd' from file name pattern 'E:/Intellij_IDEA/Tomcat Servers/myOrderica-7.0.56/logs/myorderica.%d{yyyy-MM-dd}.%i.log'.
17:07:43,836 |-INFO in ch.qos.logback.core.rolling.SizeAndTimeBasedFNATP@12e07f77 - Roll-over at midnight.
17:07:43,836 |-INFO in ch.qos.logback.core.rolling.SizeAndTimeBasedFNATP@12e07f77 - Setting initial period to Sat Jul 04 17:07:43 IST 2015
17:07:43,844 |-INFO in ch.qos.logback.core.joran.action.NestedComplexPropertyIA - Assuming default type [ch.qos.logback.classic.encoder.PatternLayoutEncoder] for [encoder] property
17:07:43,855 |-INFO in ch.qos.logback.core.rolling.RollingFileAppender[FILE] - Active log file name: E:/Intellij_IDEA/Tomcat Servers/myOrderica-7.0.56/logs/myorderica.2015-07-04.0.log
17:07:43,855 |-INFO in ch.qos.logback.core.rolling.RollingFileAppender[FILE] - File property is set to [null]
17:07:43,856 |-INFO in ch.qos.logback.classic.joran.action.LevelAction - ROOT level set to INFO
17:07:43,856 |-INFO in ch.qos.logback.core.joran.action.AppenderRefAction - Attaching appender named [STDOUT] to Logger[ROOT]
17:07:43,857 |-INFO in ch.qos.logback.core.joran.action.AppenderRefAction - Attaching appender named [FILE] to Logger[ROOT]`

**Comment by felixbarny** [comment]
Things you could try:

Set a breakpoint in the constructor of HttpRequestMonitorFilter to see if it gets instantiated.
If it does, probably something goes wrong in HttpRequestMonitorFilter#injectHtml. 

If you can't find the error, you can send me your application so that I can take a look on it.

**Comment by narender-balauda** [comment]
Hi Felix,

Thanks for your responses. I was out and couldn't post you back.

Somehow i can't send you my application, So, I am converting my application to Maven based now.

Lets see how it works.

Thanks for the support,
Naren

**Comment by felixbarny** [comment]
That's probably a better choice anyway. Feel free to reopen this issue or another one if necessary.
