### ISSUE TITLE
Combined host metrics show wrong values immediately after starting monitoring

### ISSUE THREAD

**Issue by WalterLeinert** [stagemonitor/stagemonitor#87]
When starting monitoring (e.g. network or disk io) on two different servers one shortely after the other metrics for All hosts shows much higher values than the sum of values for each indiviual host.
Selecting a time frame after startup of both servers shows expected values.

**Comment by felixbarny** [comment]
This issue is fixed in the new Elasticsearch based Grafana 2.0 dashboard
