### ISSUE TITLE
MainStageMonitorClassFileTransformer intervenes with webapps if multiple are deployed on 1 application server

### ISSUE THREAD

**Issue by tstaals** [stagemonitor/stagemonitor#88]
When you have a tomcat with multiple webapps, where only one application has the stagemonitor libs, it also tries to instrument the classes in the other webapps.

Im not complety sure but I believe its caused by using ClassPool.getDefault() in MainStageMonitorClassFileTransformer

In this case the apps have there own lib directory in the WEB-INF. 
Dont know how this will work when using multiple webapps in tomcat and the libaries in the shared lib directory.

**Comment by felixbarny** [comment]
Could you try out the master? It should already be fixed there.

**Comment by tstaals** [comment]
Im sorry did not see that, should have looked better, there is not a release version of the master yet right?

**Comment by felixbarny** [comment]
Not yet, but hopefully very soon. It would be a great help to me if you could try out the current master.

**Comment by tstaals** [comment]
Im building it right know, report back soon

**Comment by tstaals** [comment]
The warnings are better handled, but it still tries to Transformer classes from the webapp that doesnt include the stagemonitor lib files.

Most of these classed are generated on request for your information

![image](https://cloud.githubusercontent.com/assets/513068/8575047/336eac4c-259a-11e5-9f05-fa755b53c8c9.png)

**Comment by felixbarny** [comment]
Could you try again with the latest master?

**Comment by felixbarny** [comment]
In case its not working, could you tell me how to reproduce the problem? Then I'll try to make a fix before the next release that is scheduled before next week.

**Comment by tstaals** [comment]
Just a qucik heads up, I tried the lastest master yesterday, unfortunally the webapp did seem to responds anymore. Also logging was complete blank, so I have to look in that further to see what went wrong.

**Comment by felixbarny** [comment]
Any chance you can share your application with me?

**Comment by tstaals** [comment]
Im sorry i'm not at liberty to share the application, but the latest master seems to work for us. Dont know yet why it hanged the first try.

But it seems to work right now and its responsive so thats great. When im back from my holiday I will get to work to deploy it in out acceptance systems and see how it performs under load.

The issue could be closed I guess, thx for the awesom work.

**Comment by felixbarny** [comment]
:)
