### ISSUE TITLE
Application keep loading & became unresponsive

### ISSUE THREAD

**Issue by narender-balauda** [stagemonitor/stagemonitor#91]
Hi,

I am using `stagemonitor 0.15.2` with Spring+Hibernate+Maven.
First it showed me an exception while compiling:
`org.stagemonitor.javassist.NotFoundException: org.jaxen.VariableContext`

After that i added dependency in pom:
       `<dependency>
            <groupId>jaxen</groupId>
            <artifactId>jaxen</artifactId>
            <version>1.1.6</version>
        </dependency>`

Now there is no exception in console:
`org.stagemonitor.javassist.NotFoundException: org.jaxen.VariableContext`

But my home page is blank and keeps loading and become unresponsive.
I am using 'Spring security filters', 'some custom filters' and my application a multi-tenancy application.

Any clue ?

**Comment by felixbarny** [comment]
Please try again with stagemonitor 0.16.0

**Comment by narender-balauda** [comment]
Hi Felix,

Thanks for the quick response.

I just used `stagemonitor 0.16.0` but no luck. 
Same issue `Home page keeps loading`.

Below are the logs:
`[INFO]  2015-07-13 19:32:32.538 [RMI TCP Connection(3)-127.0.0.1] o.s.core.instrument.MainStagemonitorClassFileTransformer - Registering ExceptionMeteredInstrumenter
[INFO]  2015-07-13 19:32:32.538 [RMI TCP Connection(3)-127.0.0.1] o.s.core.instrument.MainStagemonitorClassFileTransformer - Registering MeteredInstrumenter
[INFO]  2015-07-13 19:32:32.553 [RMI TCP Connection(3)-127.0.0.1] o.s.core.instrument.MainStagemonitorClassFileTransformer - Registering TimedInstrumenter
[INFO]  2015-07-13 19:32:32.553 [RMI TCP Connection(3)-127.0.0.1] o.s.core.instrument.MainStagemonitorClassFileTransformer - Registering GaugeInstrumenter`

`[INFO]  2015-07-13 19:32:54.292 [RMI TCP Connection(3)-127.0.0.1] org.stagemonitor.web.configuration.ConfigurationServlet - Registering configuration Endpoint /stagemonitor/configuration. You can dynamically change the configuration by issuing a POST request to /stagemonitor/configuration?key=stagemonitor.config.key&value=configValue&stagemonitor.password=password. If the password is not set, dynamically changing the configuration is not available. The password can be omitted if set to an empty string.`

`[INFO]  2015-07-13 19:34:16.036 [pool-1-thread-1] org.stagemonitor.core.Stagemonitor - Initializing plugin CorePlugin
[INFO]  2015-07-13 19:34:16.222 [pool-1-thread-1] org.stagemonitor.core.Stagemonitor - Initializing plugin JdbcPlugin
[INFO]  2015-07-13 19:34:16.227 [pool-1-thread-1] org.stagemonitor.core.Stagemonitor - Initializing plugin JvmPlugin
[INFO]  2015-07-13 19:34:16.461 [pool-1-thread-1] org.stagemonitor.core.Stagemonitor - Initializing plugin RequestMonitorPlugin
[INFO]  2015-07-13 19:34:16.463 [pool-1-thread-1] org.stagemonitor.core.Stagemonitor - Initializing plugin WebPlugin
[INFO]  2015-07-13 19:34:16.477 [pool-1-thread-1] org.stagemonitor.core.Stagemonitor - Measurement Session is initialized: [application=Orderica Cart] [instance=localhost] [host=NareN]`

Here is screenshot of home page:

![image](https://cloud.githubusercontent.com/assets/11943748/8651882/2bdf64f0-2999-11e5-99e7-ea43235db1a9.png)


Thanks

**Comment by felixbarny** [comment]
What are your settings in stagemonitor.properties?

**Comment by narender-balauda** [comment]
My `stagemonitor.properties` contains only one line:
`stagemonitor.instrument.include=com.naren`

**Comment by felixbarny** [comment]
I have noticed similar issues when the call tree gets too big (>1000-3000).
Could you debug the js and tell me how big your call tree is?
<img width="718" alt="bildschirmfoto 2015-07-13 um 17 28 28" src="https://cloud.githubusercontent.com/assets/2163464/8653460/ca221460-2984-11e5-85c9-6e5e9d06f1b9.png">

One way to make it smaller is to set `stagemonitor.profiler.minExecutionTimeNanos=10000000`. This only shows methods that took longer than 10ms. Another option would be to make some excludes with `stagemonitor.instrument.exclude=com.naren.domain`. It also seems that Firefox handles big Call Trees better than Chrome.

But fist check the actual size of the Call Tree to check if that is the actual issue.

**Comment by narender-balauda** [comment]
Okay, Felix i will look into it and post you the result.
Thanks in advance.

**Comment by narender-balauda** [comment]
Hi Felix,

Any clue? I am stuck :(

**Comment by felixbarny** [comment]
Woha, that's a lot! Have you tried setting `stagemonitor.profiler.minExecutionTimeNanos=10000000`?

**Comment by narender-balauda** [comment]
Yes, Let me include a package which contain a few classes only.

**Comment by narender-balauda** [comment]
No, luck

**Comment by felixbarny** [comment]
Maybe increasing the min execution time to `stagemonitor.profiler.minExecutionTimeNanos=100000000`?

**Comment by narender-balauda** [comment]
min execution didn't helped.

Also now i am getting this in logs:

```
INFO: Trying to load agent @ E:\Intellij_IDEA\MyProjMaven_10072015\target\my-proj-web-1.0-SNAPSHOT\WEB-INF\lib\stagemonitor-javaagent-0.16.0.jar
[INFO]  2015-07-14 15:42:52.147 [RMI TCP Connection(3)-127.0.0.1] o.s.core.instrument.MainStagemonitorClassFileTransformer - Registering ExceptionMeteredInstrumenter
[INFO]  2015-07-14 15:42:52.148 [RMI TCP Connection(3)-127.0.0.1] o.s.core.instrument.MainStagemonitorClassFileTransformer - Registering MeteredInstrumenter
[INFO]  2015-07-14 15:42:52.205 [RMI TCP Connection(3)-127.0.0.1] o.s.core.instrument.MainStagemonitorClassFileTransformer - Registering TimedInstrumenter
[INFO]  2015-07-14 15:42:52.209 [RMI TCP Connection(3)-127.0.0.1] o.s.core.instrument.MainStagemonitorClassFileTransformer - Registering GaugeInstrumenter
[INFO]  2015-07-14 15:42:52.466 [RMI TCP Connection(3)-127.0.0.1] o.s.core.instrument.MainStagemonitorClassFileTransformer - Registering ConnectionMonitoringInstrumenter
[INFO]  2015-07-14 15:42:52.494 [RMI TCP Connection(3)-127.0.0.1] o.s.core.instrument.MainStagemonitorClassFileTransformer - Registering ProfilingInstrumenter
[INFO]  2015-07-14 15:42:52.506 [RMI TCP Connection(3)-127.0.0.1] o.s.core.instrument.MainStagemonitorClassFileTransformer - Registering MonitorRequestsInstrumenter
[INFO]  2015-07-14 15:42:52.523 [RMI TCP Connection(3)-127.0.0.1] o.s.core.instrument.MainStagemonitorClassFileTransformer - Registering ElasticsearchSearchQueryInstrumenter
[INFO]  2015-07-14 15:42:52.534 [RMI TCP Connection(3)-127.0.0.1] o.s.core.instrument.MainStagemonitorClassFileTransformer - Registering SpringMvcRequestNameDeterminerInstrumenter
[INFO]  2015-07-14 15:42:53.240 [RMI TCP Connection(3)-127.0.0.1] o.s.core.instrument.MainStagemonitorClassFileTransformer - Retransforming 0 classes...
[INFO]  2015-07-14 15:42:53.249 [RMI TCP Connection(3)-127.0.0.1] o.s.core.instrument.MainStagemonitorClassFileTransformer - Retransformed 0 classes in 1107 ms
```

**Comment by felixbarny** [comment]
Your call tree is still too large if it only contains method calls that took longer than 100ms?? How long does a Request to your application take?

The log is looking good.

**Comment by narender-balauda** [comment]
What you mean by request ?
You mean running the app from intellij ?
```
[2015-07-14 03:59:20,701] Artifact my-proj-web:war exploded: Deploy took 134,540 milliseconds
```
Or opening home page after application start ?

**Comment by felixbarny** [comment]
By request I mean HTTP request - how long it takes to open a page in your browser. When the setting `stagemonitor.profiler.minExecutionTimeNanos=100000000` is active, the call tree only contains method call that took longer than 100ms. If your Call Tree is still to large then that would imply that processing a request takes ages and a lot of methods take over 100ms to proceed.

Is the size of the call tree decreasing when adjusting the settings? Maybe the stagemonitor.properties file is not picked up correctly. You could try to set `stagemonitor.applicationName=test`. Then the logs should contain `[INFO]  2015-07-13 19:34:16.477 [pool-1-thread-1] org.stagemonitor.core.Stagemonitor - Measurement Session is initialized: [application=test] [instance=localhost] [host=NareN]`

**Comment by narender-balauda** [comment]
I can't figure out the time to open a page in browser because as soon as i run the project/app my browser become unresponsive.

Call tree size varies every time i restart tomcat sometimes less, sometimes more.
After `stagemonitor.profiler.minExecutionTimeNanos=10000000` the call tree size is: `20403`

After adding `stagemonitor.applicationName=test` logs still showing:
```
[INFO]  2015-07-14 16:50:02.046 [pool-1-thread-1] org.stagemonitor.core.Stagemonitor - Measurement Session is initialized: [application=My Proj] [instance=localhost] [host=NareN]
```

**Comment by felixbarny** [comment]
Aha, now we have found the problem. The stagemonitor.properties file seems to be at the wrong location. Are you using maven? is it under src/main/resouces? Do you create a war file? Is it under /WEB-INF/classes/stagemonitor.properties?

**Comment by narender-balauda** [comment]
Okay,
Yes i am using Maven and `stagemonitor.properties` was under `src/main/resouces/config` folder. But i included it using `PropertyPlaceholderConfigurer`.

Yes i do create a war.
Let me put it under `src/main/resouces` and check.

**Comment by narender-balauda** [comment]
Hi Felix,

It worked with location `src/main/resouces` & `stagemonitor.profiler.minExecutionTimeNanos=10000000`, thanks a lot.
I don't know why it was not accepting the `stagemonitor.properties` when it was under `src/main/resouces/config` because i already included it under `PropertyPlaceholderConfigurer` bean and my logs showed that it was reading the file.

Anyways thanks for the help. 

One questions though:
How can i put `stagemonitor.properties` at custom location ?

**Comment by felixbarny** [comment]
stagemonitor.properties have nothing to do with Spring's PropertyPlaceholderConfigurer.

You can probably leave out the minExecutionTime. 

1. That is currently not supported
2. disable what?

**Comment by narender-balauda** [comment]
Okay.

Without `stagemonitor.profiler.minExecutionTimeNanos=10000000` the call tree size >3000 and browser become unresponsive. So i think i need this.

Can we disable Stagemonitor to run using any property value in `stagemonitor.properties`?

**Comment by felixbarny** [comment]
See https://github.com/stagemonitor/stagemonitor/wiki/Configuration-Options#activate-stagemonitor

If you want different configuration depending on the environment (dev, prod) see https://github.com/stagemonitor/stagemonitor/wiki/Configuration#environment-specific-configuration

**Comment by felixbarny** [comment]
If you feel the call tree shows too few information, you can always try to lower the minExecutionTime.

**Comment by narender-balauda** [comment]
Thanks a bunch :+1: :+1: :+1: 
The conversation with you was very helpful and knowledgeable.

**Comment by felixbarny** [comment]
You're very welcome, glad I could help :-)
