### ISSUE TITLE
Running stagemonitor without servlet support

### ISSUE THREAD

**Issue by DanielYWoo** [stagemonitor/stagemonitor#94]
My service layer is not web-based, it's thrift-RPC based, can I use stagemonitor without servlet context?

**Comment by felixbarny** [comment]
Stagemonitor can be integrated manually.

# Initialize stagemonitor
The first thing is to make sure stagemonitor's ClassFileTransformer gets initialized. There are two ways to do that.

## Initialize via javaagent
Start your application with the -javaagent option: ` -javaagent:/path/to/stagemonitor-javaagent-<version>.jar`

## Programatic initialization
Just call `Stagemonitor.init()` as early as possible in the lifecycle of your application. Ideally call it in the first line of your `main` method. The earlier stagemonitor is initialized the less files have to be retransformend, which is a expansive operation.

# Monitor your methods

## Declaratively
Annotate the entry points of your application with `@MonitorRequests`. The request will be named after the name of the method.

```
@MonitorRequests
public Object myEntryPoint(String arg1, Integer arg2) {
    doWork();
}
````

## Programatically

```
private static final RequestMonitor requestMonitor = configuration.getRequestMonitor();

public Object myEntryPoint(String arg1, Integer arg2) {
    try {
        requestMonitor.monitorStart(new org.stagemonitor.requestmonitor.MonitoredMethodRequest("MyMethod.myEntryPoint()", null, arg1, arg2));
        doWork();
    } catch (Exception e) {
        requestMonitor.recordException(e);
    } finally {
        requestMonitor.monitorStop();
    }
}
````
