### ISSUE TITLE
@MonitorRequests does not do what the documentation promises

### ISSUE THREAD

**Issue by marcust** [stagemonitor/stagemonitor#96]
The documentation of @MonitorRequests says:
 > By annotating a type with MonitorRequests, a Timer will be created for all its public methods and the 
 > call stack of these methods will be recorded.

But the implementation in MonitorRequestsInstrumenter reads
```
		for (CtMethod ctMethod : ctClass.getDeclaredMethods()) {
			MonitorRequests monitorRequests = (MonitorRequests) ctMethod.getAnnotation(MonitorRequests.class);
			if (monitorRequests != null) {
				monitorMethodCall(ctClass, ctMethod);
			}
		}
```

and nothing about public methods. Am I reading this wrong or are the docs off?

**Comment by felixbarny** [comment]
You are right. The implementation is not according to the spec. The current implementation only supports annotating methods. Should be easy to fix though. Do you have time to do a pull request?

**Comment by marcust** [comment]
I'll have a look
